feat: add onChange, validation, async/await
Yandex-SpaceY/SpaceY pull request #17
Opened 2021-06-23 09:07 UTC by SupergroverNN

Добавлены onChange для форм, добавлены async/await , прикручена валидация, отслеживание состояния кнопки в зависимости от наличия ошибок в инпутах

2021-06-23 10:10 UTC, ValeriaKoliagina commented on src/constants/commonConstants.ts
> +export type loginKeys = keyof loginType;
Привет! Забыл пустую строку добавить и давай может разделим эти константы? Что к логинке относится - вынесем в отдельный файл и т.д. Чтобы в common лежали только те вещи, которые действительно будут много где использоваться по всему приложению

2021-06-23 10:10 UTC, ValeriaKoliagina commented on src/pages/login/Login.tsx
> +import { buttonDisabler, checkFieldNotEmpty, checkPassword } from 'utils';
Про buttonDisabler - я сначала подумала, что это не функция, а существительное, сущность что ли. Может если это функция стоит ее переименовать немного?

2021-06-23 10:10 UTC, ValeriaKoliagina commented on src/pages/login/Login.tsx
> +  const [ state, setState ] = useState<loginType>(DEFAULT_LOGIN_STATE);
Если честно, не знаю, насколько это хорошая идея хранить в стейте прям сразу весь объект. Мне кажется, логичнее было бы хранить отдельные поля - с ними и работать было бы потом легче. Взываю к силе @kotosha-real

2021-06-23 10:10 UTC, ValeriaKoliagina commented on src/pages/login/Login.tsx
> +  const loginHandler = async () => {
Поскольку это форма, было бы прикольно чтобы по Enter форма тоже отправлялась. Но это так - FYI

2021-06-23 10:10 UTC, ValeriaKoliagina commented on src/pages/profileEdit/ProfileEdit.tsx
>    useEffect(() => {
Предлагаю useEffect писать по возможности после useState, - для наглядности

2021-06-23 10:10 UTC, ValeriaKoliagina commented on src/utils/validations.ts
> +  if (errors && button?.disabled === false) {
```suggestion
  if (errors && !button?.disabled) {
```

2021-06-23 10:10 UTC, ValeriaKoliagina commented on src/utils/validations.ts
> +  } else if (!errors && button?.disabled === true) {
```suggestion
  } else if (!errors && button?.disabled) {
```

2021-06-23 10:10 UTC, ValeriaKoliagina commented on src/utils/validations.ts
> +const buttonDisabler = (): void => {
А может быть такая ситуация, что у нас будет форма с несколькими кнопками - к примеру, save , cancel. И задизейблить нам надо только одну...

2021-06-24 07:12 UTC, kotosha-real commented on src/utils/validations.ts
> +  if (errors && button?.disabled === false) {
Здесь есть разница

```
var button = { disabled: false }
var obj = {}
!button?.disabled // true
!obj?.disabled // true
button?.disabled === false // true
obj?.disabled === false // false
```

Хотя, в нашем случае не так важно

2021-06-24 07:13 UTC, kotosha-real commented on src/utils/validations.ts
> +const buttonDisabler = (): void => {
Состояние disabled для кнопки должно передаваться из родтельской формы, ошибки которой должны лежать внутри её стейта. Если во время разработки на реакте/вью/другом модном фреймворке вам приходится прибегать к ручным манипуляциям с домом, в 99% случаев что-то идёт не так)

2021-06-27 12:18 UTC, kotosha-real commented on src/pages/login/Login.tsx
> +  const [ state, setState ] = useState<loginType>(DEFAULT_LOGIN_STATE);
Это норм, представь форму из 10 полей. Чтобы отправить её на бэк тебе надо будет их все собрать, и вот это уже совсем неудобно. Другое дело, что state — явно неподходящее название

2021-06-27 12:19 UTC, kotosha-real commented on src/pages/login/Login.tsx
> +  const [ state, setState ] = useState<loginType>(DEFAULT_LOGIN_STATE);
Ещё тут просится реюз формы как отдельного компонента, потому что с огромной вероятностью логика валидации и отправки, а также внешний вид будут едиными для всех форм на проекте

2021-06-27 12:53 UTC, SupergroverNN commented on src/constants/commonConstants.ts
> +export type loginKeys = keyof loginType;
fixed (надеюсь)

2021-06-27 12:58 UTC, SupergroverNN commented on src/pages/login/Login.tsx
> +import { buttonDisabler, checkFieldNotEmpty, checkPassword } from 'utils';
сменил название на checkButtonDisable

2021-06-27 13:01 UTC, SupergroverNN commented on src/pages/login/Login.tsx
> +  const [ state, setState ] = useState<loginType>(DEFAULT_LOGIN_STATE);
название "state" выбрано из-за аналогии со стейтом классового компонента) а так, наверное можно переименовать стейты в loginState, profileState..

2021-06-27 13:26 UTC, SupergroverNN commented on src/pages/profileEdit/ProfileEdit.tsx
>    useEffect(() => {
переместил все что было лишнего до useEffect под него

2021-06-27 13:28 UTC, SupergroverNN commented on src/utils/validations.ts
> +  if (errors && button?.disabled === false) {
не задумывался раньше над тем, что свойства html элементов также можно проверять на true / false
fixed

2021-06-27 13:39 UTC, SupergroverNN commented on src/utils/validations.ts
> +const buttonDisabler = (): void => {
переименовал функцию. Дизейбл хранится в стейте компонента ее используемого и передается в компонент кнопки из него, вычисляясь функцией.

2021-06-27 13:41 UTC, SupergroverNN commented on src/utils/validations.ts
> +  } else if (!errors && button?.disabled === true) {
fixed

2021-06-27 14:46 UTC, StopNGo commented on src/constants/commonConstants.ts
> +export type loginKeys = keyof loginType;
Все равно даже в самом гите светит No new line at the end of file ((
Приттиер с линтером должны же править. Ну или на худой конец в VSCode есть соответствующтй плагин
https://marketplace.visualstudio.com/items?itemName=jdforsythe.add-new-line-to-files
В для таких слепых как, есть еще и визуализация:
https://marketplace.visualstudio.com/items?itemName=msfukui.eof-mark

2021-06-27 14:48 UTC, StopNGo commented on src/constants/commonConstants.ts
> +export type loginKeys = keyof loginType;
Ты, наверное, не запушил последние правки...

2021-06-27 15:10 UTC, SupergroverNN commented on src/pages/login/Login.tsx
> +  const loginHandler = async () => {
fixed

2021-06-28 15:33 UTC, ValeriaKoliagina approved these changes

2021-06-30 14:08 UTC, kotosha-real requested changes
Классная работа!
Оставил комменты, если будут вопросы — смело пиши

2021-06-30 14:08 UTC, kotosha-real commented on .prettierrc
> +  "arrowParens": "avoid"
❗️
В тайпскриптовом проекте это зло)
Ты не сможешь убрать скобки, если захочешь написать аннотацию типов и возвращаемого значения. А раз ты по факту обязан это делать для полноценного покрытых тайпингами функций, лучше это использовать везде, потому что консистентность — это хорошо)

2021-06-30 14:08 UTC, kotosha-real commented on src/constants/commonConstants.ts
> +export type userKeys = keyof userType;
❗️
Константы должны именоваться одинаково везде
```suggestion
export type USER_TYPE = typeof DEFAULT_USER_STATE;

export type USER_KEYS = keyof userType;
```

2021-06-30 14:08 UTC, kotosha-real commented on src/constants/commonConstants.ts
> +export type loginKeys = keyof loginType;
❗️
Аналогично
```suggestion
export type LOGIN_TYPE = typeof DEFAULT_LOGIN_STATE;

export type LOGIN_KEYS = keyof loginType;
```

2021-06-30 14:08 UTC, kotosha-real commented on src/pages/login/Login.tsx
> +  const [ state, setState ] = useState<loginType>(DEFAULT_LOGIN_STATE);
❗️
`loginState` пойдёт)

2021-06-30 14:08 UTC, kotosha-real commented on src/pages/login/Login.tsx
> +    const newDisable = checkButtonDisable();
❗️
Это должно работать наоборот)
**Как сейчас:** валидация ввода происходит прямо в пропсе `errorText` инпутов, это заставляет для дисейбла кнопки отправки серчить все инпуты и смотреть есть ли у них класс с ошибкой
**Как надо:** валидация производится централизованно в компоненте с формой. Так компонент сам будет знать, когда ему нужно запретить сабмит формы и сможем обойтись без посторонних хелперов

В одном из пров я общался с @ValeriaKoliagina насчёт затаскивания отдельных либ для формы + валидации (Formik + Yup), попробуйте с ней посинкаться на этот счёт, потому что этот момент ярко иллюстрирует то, о чём я говорил: когда нет централизованной валидации, приходится придумывать неоптимальные велосипеды

2021-06-30 14:08 UTC, kotosha-real commented on src/pages/login/Login.tsx
> +          <Button disabled={disabled} onClick={loginHandler}>{BUTTON_TEXTS.SIGNIN}</Button>
❗️
Это тот же `onSubmitHandler`, `loginHandler` можно влить в `onSubmitHandler`, а его самого убить

2021-06-30 14:08 UTC, kotosha-real commented on src/utils/validations.ts
>  };
❗️
Писал в одном из мест, где она применяется. Так делать плохо, давай выпилим)

2021-06-30 14:08 UTC, kotosha-real commented on src/pages/signup/Signup.tsx
> +            <Input value={state.first_name} name='first_name' title='first name' onChange={onChange} errorText={checkFieldNotEmpty(state.first_name)} />
❗️
Длинновые строки получились, давай слегка отформатируем. По самой логике выше писал, что в `errorText` надо передавать не просто функцию, которая "на месте" вычислит ошибку, а хранимую в самом компоненте
```suggestion
            <Input
              value={state.first_name}
              name='first_name'
              title='first name'
              onChange={onChange}
              errorText={checkFieldNotEmpty(state.first_name)}
            />
```

2021-06-30 14:08 UTC, kotosha-real commented on src/pages/profileEdit/ProfileEdit.tsx
> +            <Input value={state.first_name} name='first_name' title='first name' onChange={onChange} errorText={checkFieldNotEmpty(state.first_name)} />
❗️
Аналогично по всему файлу (и везде, где оно встречается), длинные строчки + логика

2021-06-30 14:18 UTC, ValeriaKoliagina commented on src/pages/login/Login.tsx
> +    const newDisable = checkButtonDisable();
@kotosha-real а мы не будем подключать что-то типа redux-form? Если в планах нашего проекта такого нету, то я за переделку на предложенный вариант

2021-06-30 18:16 UTC, SupergroverNN commented on src/constants/commonConstants.ts
> +export type userKeys = keyof userType;
я думал что к типам это не применяется =)

2021-06-30 18:19 UTC, SupergroverNN commented on src/pages/login/Login.tsx
> +          <Button disabled={disabled} onClick={loginHandler}>{BUTTON_TEXTS.SIGNIN}</Button>
изначально предполагалось что у кнопки может не быть onClick, например при type="submit", но эта идея не прижилась в одном из предыдущих моих ПРов. поправлю )

2021-07-01 19:55 UTC, SupergroverNN commented on src/pages/login/Login.tsx
> +  const [ state, setState ] = useState<loginType>(DEFAULT_LOGIN_STATE);
fixed

2021-07-01 19:57 UTC, SupergroverNN commented on .prettierrc
> +  "arrowParens": "avoid"
блин, да. fixed

2021-07-01 19:57 UTC, SupergroverNN commented on src/constants/commonConstants.ts
> +export type userKeys = keyof userType;
fixed

2021-07-01 19:58 UTC, SupergroverNN commented on src/constants/commonConstants.ts
> +export type loginKeys = keyof loginType;
fixed

2021-07-01 20:07 UTC, SupergroverNN commented on src/pages/login/Login.tsx
> +          <Button disabled={disabled} onClick={loginHandler}>{BUTTON_TEXTS.SIGNIN}</Button>
fixed

2021-07-01 20:36 UTC, SupergroverNN commented on src/pages/profileEdit/ProfileEdit.tsx
> +            <Input value={state.first_name} name='first_name' title='first name' onChange={onChange} errorText={checkFieldNotEmpty(state.first_name)} />
fixed

2021-07-01 20:48 UTC, kotosha-real commented on src/constants/commonConstants.ts
> +export type userKeys = keyof userType;
Если они лежат в константах, то именоваться должны как константы. Дискуссионный вопрос — должны ли они лежать константах. Но это уже совсем другая история)

2021-07-01 21:06 UTC, StopNGo approved these changes

2021-07-01 21:23 UTC, kotosha-real approved these changes
🕵🏻‍♂️
Молодец!
Ещё пару мест надо поправить и можно мержить

2021-07-01 21:23 UTC, kotosha-real commented on src/pages/login/Login.tsx
> +  };
❗️
Он нигде больше не юзается, поэтому не нужен. Перенеси его логику в `onSubmitHandler`

2021-07-01 21:23 UTC, kotosha-real commented on src/pages/login/Login.tsx
> +          <input type='submit' className='hidden' />
❓
Есть ли смысл в скрытом инпуте?

2021-07-01 21:23 UTC, kotosha-real commented on src/pages/signup/Signup.tsx
> +  };
❗️
Аналогично `loginHandler`, давай выпилим

2021-07-01 21:23 UTC, kotosha-real commented on src/pages/profileEdit/ProfileEdit.tsx
> +    setUserState(newState);
🧐
```suggestion
    setUserState(Object.assign(userState, { [name]: value }))
```

2021-07-01 21:23 UTC, kotosha-real commented on src/pages/profileEdit/ProfileEdit.tsx
>        .catch(err => console.error(err?.response?.data?.reason || err?.message || ERROR_CONSTANTS.DEFAULT_ERROR));
🧐
Тут тоже можно (но пока необязательно) переписать на async/await

2021-07-02 11:55 UTC, SupergroverNN commented on src/pages/login/Login.tsx
> +  };
fixed

2021-07-02 11:58 UTC, SupergroverNN commented on src/pages/login/Login.tsx
> +          <input type='submit' className='hidden' />
уххх, это был секретный инпут для того чтобы работал по ентеру onSubmit, но похоже работает и без него O.o

2021-07-02 12:01 UTC, SupergroverNN commented on src/pages/login/Login.tsx
> +          <input type='submit' className='hidden' />
fixed

2021-07-02 12:01 UTC, SupergroverNN commented on src/pages/signup/Signup.tsx
> +  };
fixed

2021-07-02 12:04 UTC, SupergroverNN commented on src/pages/profileEdit/ProfileEdit.tsx
> +    setUserState(newState);
fixed, в данном компоненте и в тех, где использовался такой же подход.

2021-07-02 12:04 UTC, SupergroverNN commented on src/pages/profileEdit/ProfileEdit.tsx
>        .catch(err => console.error(err?.response?.data?.reason || err?.message || ERROR_CONSTANTS.DEFAULT_ERROR));
fixed

2021-07-02 13:21 UTC, merged