Game page with dynamic menu
Yandex-SpaceY/SpaceY pull request #18
Opened 2021-06-23 10:55 UTC by StopNGo

Все привет! Прошу просмотреть и (что не мало важно) протестить следующий апдейт. Включает в себя - динамический компонент меню, страницу игры, которая использует этот компонент. По сути, страница Dashboard на будет уже не нужна. Просброс стейтов сделано через костыли, я так понимаю, все решается глобальными стейтами, но сделал, как смог) Может кто подскажет, как сделать такие пробросы без глобальных стейтов более грамотно. Спасибо!

2021-06-23 19:35 UTC, ValeriaKoliagina commented on src/components/gameCanvas/GameCanvas.tsx
> +    }
Можно было бы написать `toggleMenu && toggleMenu()` - но это опционально

2021-06-23 19:35 UTC, ValeriaKoliagina commented on src/components/gameCanvas/GameCanvas.tsx
> +    }
А нам нужна это повторяющаяся логика в обоих useEffect? Можно это можно как-то объединить?

2021-06-23 19:35 UTC, ValeriaKoliagina commented on src/components/gameCanvas/GameCanvas.tsx
> +    case MENU_ACTIONS.GAME_RESUME:
тут вроде как не хватает пробела, перед case - не должно быть на одном уровне со switch

2021-06-23 19:35 UTC, ValeriaKoliagina commented on src/components/gameCanvas/GameCanvas.tsx
> +      break;
можно объединить как 
`case MENU_ACTIONS.GAME_RESTART:
case MENU_ACTIONS.GAME_START:`

Поскольку у тебя повторяется логика `if (resetMenuAction) {
        resetMenuAction();
      }` ее можно вынести после switch

2021-06-23 19:35 UTC, ValeriaKoliagina commented on src/components/gameCanvas/GameCanvas.tsx
> +        <div>Score: {score}</div>
А как же константы?

2021-06-23 19:35 UTC, ValeriaKoliagina commented on src/components/gamecanvas/GameCanvas.tsx
> +import React, { FC, useEffect, useCallback, useRef, useState, ReactElement } from 'react';
Обрати внимание, ты снова добавляешь папку gamecanvas - ту, которая с маленькой буквы

2021-06-23 19:35 UTC, ValeriaKoliagina commented on src/components/menu/menu.tsx
> +import { GAME_NAME, MENU_ITEMS } from 'constants/commonConstants';
Если честно, не очень понимаю, зачем все класть в commonConstants...

2021-06-23 19:35 UTC, ValeriaKoliagina commented on src/components/menu/menu.tsx
> +    <div className='menu' style={{ display: isShown ? 'flex' : 'none' }}>
А мы можем не использовать инлайн-стили?

2021-06-23 19:35 UTC, ValeriaKoliagina commented on src/components/menu/menu.tsx
> +          } else if (action) {
Если у нас возможно только 2 состояния, может стоит сделать `if (route) { return ...}; return ( <span>...)`

2021-06-23 19:35 UTC, ValeriaKoliagina commented on src/components/menu/menu.tsx
> +                }
```suggestion
    handleAction && handleAction()
```
Мне кажется так будет более читабельно и не будет кучи ифов в ифах

2021-06-23 19:35 UTC, ValeriaKoliagina commented on src/components/menu/menu.tsx
> +        )}
непонятно, как так получилось, что они у тебя на одном уровне

2021-06-23 19:35 UTC, ValeriaKoliagina commented on src/constants/commonConstants.ts
> +export const MENU_ACTIONS = {
enum?

2021-06-23 19:35 UTC, ValeriaKoliagina commented on src/pages/dashboard/dashboard.scss
> -  background: url('images/main_bg.jpg') no-repeat;
а почему ты решил убрать фон?

2021-06-23 19:35 UTC, ValeriaKoliagina commented on src/pages/game/Game.tsx
> +  const [ menuAction, setMenuAction ] = useState<string | null>(null);
несколько странно, что ты указываешь типы только для некоторый стейтов

2021-06-23 19:35 UTC, ValeriaKoliagina commented on src/pages/game/Game.tsx
> +    setIsMenuShown(!isMenuShown);
лучше `setIsMenuShown(prevValue => !prevValue);`

2021-06-23 19:35 UTC, ValeriaKoliagina commented on src/pages/game/Game.tsx
> +    if (action !== null) {
может тут будет достаточно проверки на `action`? `action && setMenuAction(action)`

2021-06-23 19:35 UTC, ValeriaKoliagina commented on src/pages/game/Game.tsx
> +    }
`!menuAction`?

2021-06-24 09:35 UTC, StopNGo commented on src/components/gameCanvas/GameCanvas.tsx
> +        <div>Score: {score}</div>
Это дебаг-информация. Юзеру будет выводиться через соответствующий компонент, ну и флаги ему не к чему.

2021-06-24 09:35 UTC, StopNGo commented on src/components/menu/menu.tsx
> +import { GAME_NAME, MENU_ITEMS } from 'constants/commonConstants';
А куда? Список элементов меню уже был там. Создать отельный файл?

2021-06-24 09:44 UTC, ValeriaKoliagina commented on src/components/menu/menu.tsx
> +import { GAME_NAME, MENU_ITEMS } from 'constants/commonConstants';
я за то, чтобы создавать отдельные файлы. Так не будет каши и проще будет найти

2021-06-24 09:53 UTC, ValeriaKoliagina commented on src/components/gameCanvas/GameCanvas.tsx
> +        <div>Score: {score}</div>
Не совсем тебя понимаю

2021-06-24 09:55 UTC, StopNGo commented on src/components/gameCanvas/GameCanvas.tsx
> +        <div>Score: {score}</div>
Я к тому, что этот кусок шаблона, просто для отладки компонента игры. Это не окончательная реализация интерфейса.

2021-06-25 21:34 UTC, StopNGo commented on src/pages/game/Game.tsx
> +    if (action !== null) {
Не, так не работает

2021-06-25 21:35 UTC, StopNGo commented on src/pages/dashboard/dashboard.scss
> -  background: url('images/main_bg.jpg') no-repeat;
Тут все уходит, так как используется компонент меню. Переделал верстку страницы просто. Но на эта страница вообще не нужна будет в дальнейшем.

2021-06-25 21:41 UTC, StopNGo commented on src/components/menu/menu.tsx
> +          } else if (action) {
Все равно тас требует проверку на наличие action

2021-06-26 13:53 UTC, ValeriaKoliagina commented on .eslintrc.json
> +			}],
А почему тут все так поехало?

2021-06-26 13:53 UTC, ValeriaKoliagina commented on src/components/gameCanvas/gameCanvas.tsx
> +        }
уже не надо, так как добавил внизу эту проверку

2021-06-26 13:53 UTC, ValeriaKoliagina commented on src/components/gameCanvas/gameCanvas.tsx
> +      >
Я так поимаю, что эта логика уйдет, поэтому тут инлайновые стили?

2021-06-26 13:53 UTC, ValeriaKoliagina commented on src/components/menu/menu.tsx
> +    <div className={`menu${isShown ? '' : ' hidden'}`}>
а почему не через cn?

2021-06-26 13:53 UTC, ValeriaKoliagina commented on src/components/gameCanvas/gameCanvas.tsx
> +import React, { FC, useEffect, useCallback, useRef, useState, ReactElement } from 'react';
А почему название файла с маленькой? мы же вроде решили с большой буквы тут писать

2021-06-26 14:07 UTC, StopNGo commented on .eslintrc.json
> +			}],
Ты локально смотрела? Такое впечатление, что гит глючит с форматированием.

2021-06-26 14:08 UTC, StopNGo commented on src/components/gameCanvas/gameCanvas.tsx
> +      >
Ну да, вроде ж обсуждали уже.

2021-06-26 15:41 UTC, ValeriaKoliagina commented on .eslintrc.json
> +			}],
не, я локально не подтягивала

2021-06-26 15:42 UTC, ValeriaKoliagina commented on src/components/gameCanvas/gameCanvas.tsx
> +      >
Обсуждали переменные - почему не в константах. А нам эти стили вообще не пригодятся? Я, наверное, не очень представляю итог...

2021-06-26 15:57 UTC, StopNGo commented on src/components/gameCanvas/gameCanvas.tsx
> +      >
Будет два отдельных компонента:
1. Вывод текущих очков и жизней поверх канваса.
2. Вывод ГеймОвер с кол-во набранных очков и обрезанным меню поверх всего.
Так что все, что тут в дивах - это все только для отладки на данным момент.

2021-06-26 16:06 UTC, ValeriaKoliagina commented on src/pages/game/Game.tsx
> +    if (action !== null) {
запустила локально, работает... Или я чего-то не вижу?

2021-06-26 16:12 UTC, StopNGo commented on src/pages/game/Game.tsx
> +    if (action !== null) {
Я наверное не догоняю новый синтаксис до конца( Да, ты права, так все ок. А я, наверное, пытался править немного по-другому.

2021-06-26 18:29 UTC, ValeriaKoliagina commented on src/components/index.tsx
> +export { TMenuItem } from 'components/menu/Menu';
а мы можем объединить, как `export { default as Menu, TMenuItem } from 'components/menu/Menu';`?

2021-06-27 12:35 UTC, SupergroverNN approved these changes

2021-06-27 12:35 UTC, SupergroverNN commented on src/components/gameCanvas/GameCanvas.tsx
> +      <div style={{
Можно ли инлайн стили заменить классом?

2021-06-27 12:57 UTC, ValeriaKoliagina approved these changes

2021-06-27 13:12 UTC, StopNGo commented on src/components/gameCanvas/GameCanvas.tsx
> +      <div style={{
Это вопрос был у Леры. Она зарезолвила его. Короче говоря - все дивы тут только для отладки игры и в дальнейшем будут заменены на компоненты (UI с очками и жизнями и компонент Game Over). Так что это сугубо быстрое временное решение для отладки.

2021-06-27 13:22 UTC, kotosha-real requested changes
Круто!
Есть немного комментов, пройдись по ним и можно мержить

2021-06-27 13:22 UTC, kotosha-real commented on .eslintrc.json
> +      { "SwitchCase": 1 }],
❗️
Даже если prettier автоматически не подхватывает такие кейсы, их можно отредачить руками и написать удобнее
```suggestion
    "indent": [
      "error",
      2,
      { "SwitchCase": 1 }
    ],
```

2021-06-27 13:22 UTC, kotosha-real commented on src/components/gameCanvas/GameCanvas.tsx
> +  resetMenuAction?: () => void;
🧐
На некоторых проектах есть правило писать коллбеки последними и в пропсах, и в интерфейсах пропсов

2021-06-27 13:22 UTC, kotosha-real commented on src/components/gameCanvas/GameCanvas.tsx
> +  const [ isGamePaused, setIsGamePauseStatus ] = useState<boolean>(true);
👍🏻

2021-06-27 13:22 UTC, kotosha-real commented on src/components/gameCanvas/GameCanvas.tsx
> +      isFirstRun.current = false;
❓
Почему решил через ref сделать?

2021-06-27 13:22 UTC, kotosha-real commented on src/components/gameCanvas/GameCanvas.tsx
> +      <canvas ref={canvasRef} className={cn('game-canvas', className)} width={375} height={667}/>
❗️
Давай уберём хардкод из ширины и высоты. Если это должны быть неизменные значения, их стоит вынести в константы в начале файла

2021-06-27 13:22 UTC, kotosha-real commented on src/constants/menuConstants.ts
> +  { title: 'start', action: MENU_ACTIONS.GAME_START },
🧐
В случаях, когда константа — это массив объектов, ожидаешь, что все эти объекты будут иметь схожую структуру. Потенциально с этим могут возникнуть проблемы. Плюс есть кейсы, когда хочется сделать какое-то действие _и_ перейти на другую страницу, например, отправить какой-то лог (первое, что в голову пришло). Поэтому я рекомендую везде явно указывать и роут, и экшен, а в момент отрисовки компонент уже будет сам решать, что из этого ему нужно и как с этим работать

2021-06-27 13:22 UTC, kotosha-real commented on src/game/gamemain.ts
> +    if (event.key === CONTROLS.SHIFT as unknown as string) {
❗️
Очень много вопросов, точнее предложений)
1. Сравнивать через key ненадёжно. В зависимости от раскладки значения будут разные. В нашем кейсе нет, ибо выбор клавиш не зависит от раскладки, но в целом не надо так)
2. Двойной каст выглядит так: тайпскрипт пытается тебе что-то сказать, а ты хочешь его заткнуть. Сравни полученный ключ (а лучше не ключ, смотри первый коммент) со значением из енама ключей, это имеет гораздо больше смысла в данной проверке

2021-06-27 13:22 UTC, kotosha-real commented on src/pages/game/Game.tsx
> +    action === MENU_ACTIONS.GAME_START && setMenuItems(MENU_ITEMS_PAUSE);
❗️
Я видел коммент Леры и в данном кейсе с ним не согласен. Подобный подход стоит использовать только в присваиваниях и JSX. В обычном js/ts читабельнее обычные условия

2021-06-27 13:22 UTC, kotosha-real commented on src/components/menu/menu.tsx
> +    <div className={cn('menu', (isShown ? '' : ' hidden'))}>
❗️
А вот тут уже можно и через `&&` написать
```suggestion
    <div className={cn('menu', isShown && ' hidden')}>
```

2021-06-27 13:22 UTC, kotosha-real commented on src/components/menu/menu.tsx
> +                  handleAction && handleAction(action);
А вот здесь лучше однострочный иф заюзать
```suggestion
                  if (handleAction) handleAction(action);
```

2021-06-27 13:28 UTC, StopNGo commented on src/game/gamemain.ts
> +    if (event.key === CONTROLS.SHIFT as unknown as string) {
Можно тут более конкретно кодом? Даже если я заменю на event.code, там строка получается. Как привести к строке через два энума?

2021-06-27 13:29 UTC, StopNGo commented on src/game/gamemain.ts
> +    if (event.key === CONTROLS.SHIFT as unknown as string) {
Тут все равно строка - https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code
а event.keyCode - depricated

2021-06-27 13:31 UTC, StopNGo commented on src/components/gameCanvas/GameCanvas.tsx
> +      isFirstRun.current = false;
Это подcмотренный способ пропуска первого запуска useEffect. Есть ли другие способы?

2021-06-27 16:33 UTC, kotosha-real commented on src/components/gameCanvas/GameCanvas.tsx
> +      isFirstRun.current = false;
Можно сделать это через стейт и добавить этот кусок стейта в зависимости соответствующего  `useEffect`
Править необязательно, просто было интересно)

2021-06-27 16:40 UTC, kotosha-real commented on src/game/gamemain.ts
> +    if (event.key === CONTROLS.SHIFT as unknown as string) {
Вот так примерно: проще читается, никаких кастов, code обеспечивает более надёжную проверку

```
if (event.code === KEYS.ESCAPE) {
  // something
}
```

Коды можно тут подсмотреть — https://keycode.info/

2021-06-27 18:32 UTC, StopNGo commented on src/game/gamemain.ts
> +    if (event.key === CONTROLS.SHIFT as unknown as string) {
Твое решение понятно. И я бы так и сделал (и, наверное, пока что так и сделаю).  Но идея была в чем. Я ее немного неправильно реализовал, но вот есть действия игры (энум), а к ним назначаются клавиши (другой энум). И в проверке события проверяется именно событие, а не конкретная клавиша. И таким образом можно быстро переназначить клавиши для все тех же событий.
И поэтому создал два энума - для конкретных клавиш, и действий игры. И мне пришлось сделать привидение к примитивному типу.
Как в это случае быть?

2021-06-27 20:17 UTC, StopNGo commented on src/game/gamemain.ts
> +    if (event.key === CONTROLS.SHIFT as unknown as string) {
Вот, даже такое есть - https://github.com/microsoft/TypeScript/issues/40793

2021-06-27 20:20 UTC, StopNGo commented on src/game/gamemain.ts
> +    if (event.key === CONTROLS.SHIFT as unknown as string) {
Тк что пришлось использовать объект)

2021-06-27 20:32 UTC, kotosha-real commented on src/game/gamemain.ts
> +    if (event.key === CONTROLS.SHIFT as unknown as string) {
Понял тебя, можно сделать так:
```
const CONTROLS = {
  PAUSE: KEYS.ESC as string,
  SHIFT: KEYS.SPACEBAR as string
}
```
Тогда все проверки корректно подхватятся

2021-06-27 20:37 UTC, StopNGo commented on src/game/gamemain.ts
> +    if (event.key === CONTROLS.SHIFT as unknown as string) {
Ну я так и сделал, см. фиксы. Только без явного указания типов. Сейчас добавлю

2021-06-27 20:41 UTC, kotosha-real approved these changes
🕵🏻‍♂️
Есть! Поправь помеченные комменты ❗️ и мержи

2021-06-27 20:41 UTC, kotosha-real commented on src/components/menu/menu.tsx
> +            } else if (action) {
❗️
Теперь у нас есть и экшен и роут, поэтому условие должно проверять и то и другое, а не одно из них. Желательно сначала экшен
```suggestion
            if (route) {
              return (
                <Link key={title} className='menu-item' to={route}>
                  {title}
                </Link>
              );
            }
            if (action) {
```

2021-06-27 20:41 UTC, kotosha-real commented on src/game/gamemain.ts
> +};
🧐
Я к предыдущей ревизии написал как можно решить это через енам, без объекта. Можно и так, и так)

2021-06-27 20:41 UTC, kotosha-real commented on src/game/gamemain.ts
> +    } else if (event.key === CONTROLS.PAUSE as unknown as string) {
❗️
Тут тоже надо поправить аналогично проверке на шифт

2021-06-27 20:41 UTC, kotosha-real commented on src/pages/game/Game.tsx
> +      if (action === MENU_ACTIONS.GAME_START) {
❗️
Перед условиями лучше делать отбивку пустой строкой
```suggestion
      setMenuAction(action);
      
      if (action === MENU_ACTIONS.GAME_START) {
```

2021-06-27 20:41 UTC, kotosha-real commented on src/components/gameCanvas/GameCanvas.tsx
> +    toggleMenu && toggleMenu();
❗️
```suggestion
    if (toggleMenu) toggleMenu();
```

2021-06-27 20:45 UTC, StopNGo commented on src/game/gamemain.ts
> +};
А разве твое решение
`const CONTROLS = {
  PAUSE: KEYS.ESC as string,
  SHIFT: KEYS.SPACEBAR as string
}`
это не через объект?

2021-06-27 21:15 UTC, kotosha-real commented on src/game/gamemain.ts
> +};
И правда
Я там хотел написать и через объект, и решение, в котором можно избавиться от одного енама и писать коды напрямую в енам контролов. В итоге всё перемешалось)
Решение, что есть сейчас вполне достаточное

2021-06-27 21:41 UTC, kotosha-real approved these changes
Теперь точно посмотрел меню)🕵🏻‍♂️

2021-06-27 21:41 UTC, kotosha-real commented on src/game/gamemain.ts
> +    } else if (event.key === CONTROLS.PAUSE) {
❗️
`code`, не `key`)

2021-06-27 21:41 UTC, kotosha-real commented on src/components/menu/menu.tsx
> +            }
❗️
Можно вот так подсократить)
```suggestion
            const callback = () => {
                  if (action && handleAction) handleAction(action); // проверка на action лишняя, но иначе тайпскрипт заругает
            }
                
            if (action) {
              return (
                <span key={title} className='menu-item' onClick={callback}>
                  {title}
                </span>
              );
            }

            if (route) {
              return (
                <Link key={title} className='menu-item' to={route} onClick={action ? callback : undefined}>
                  {title}
                </Link>
              );
            }
```

2021-06-27 21:58 UTC, StopNGo commented on src/components/menu/menu.tsx
> +            }
Извини, но если у нас есть и route и action, то в данном случае равзе не вернет только span action-а? Наверное проверку на route лучше тогда вперед?

2021-06-27 22:25 UTC, StopNGo commented on src/components/menu/menu.tsx
> +            }
Таки да, проверил, надо менять местами. Так и замерджу)

2021-06-27 22:27 UTC, merged