Init config
Yandex-SpaceY/SpaceY pull request #2
Opened 2021-06-11 01:51 UTC by StopNGo

Будет большой комментарий :)

1. При открытии любого файла проекта у меня VSCode сразу подсвечивает кучу ошибок одного типа:
Expected linebreaks to be 'LF' but found 'CRLF'.
У тебя в правилах линтера стоит:
"linebreak-style": ["error", "unix"]
При этом файлы ты сохраняешь автоматом с CRLF.
При чем автофикс именно в этом данном случае вроде как не всегда работает.
Добавил .editorconfig, который, в том числе, учитывает момент символа переноса строки.

2. Добавил автофикс сортировки свойств стиля

3. Если не добавить в eslint окружение (env), то в файле веб-пака будет много ошибок no-undef vars
Туту же на всякий случай выключил правило @typescript-eslint/no-var-requires

4. Добавил правило "comma-dangle": ["error", "never"]
Может вы предпочитаете всегда ставить трейлинг запятые, тогда можно "comma-dangle": ["error", "always"] или ["error", "always-multiline"], но сейчас можно и так и сяк.
А вообще, очень много прописано вручную правил. может следует расширять более проработанніе наборі правил? Например https://github.com/xojs/eslint-config-xo/blob/main/index.js
Тогда можно "extends": "xo" и дальше уже самое необходимое подправлять. Тут уже, например, учтен момент с лишними запятыми.

5. У меня винда, с виртуалькой пока не заморачивался (хотя можно все в докере делать), тем не менее, env переменные не работают так вот сразу. 
Для максимальной совместимости добавил пакет cross-env и передаю переменные режима в команде запусков явно

6. Перебросил дев-сервер на 3000 порт и включил historyApiFallback

7. Добавил парочку плагинов

8. Добавил хеш в имя файла (пока не пойму, как будт стили поставляться)

9. Расширил модульность общих стилей (папка style)

10. Есть предложение заменить стандартный ts-loader на https://www.npmjs.com/package/awesome-typescript-loader

2021-06-11 08:17 UTC, ValeriaKoliagina commented on webpack.config.js
> -const production = (process.env.WEBPACK_ENV || process.env.NODE_ENV) === 'production'
А почему ты вот тут поменял?

2021-06-11 08:35 UTC, StopNGo commented on webpack.config.js
> -const production = (process.env.WEBPACK_ENV || process.env.NODE_ENV) === 'production'
У меня если не пробросить эту env переменную явно, что process.env.WEBPACK_ENV, что  process.env.NODE_ENV будут undefined. Потому в скрипте package.json добавил явное назначение cross-env NODE_ENV=development, а раз только для process.env.NODE_ENV, то проверять process.env.WEBPACK_ENV вроде как уже и не нужно.

2021-06-11 08:46 UTC, ValeriaKoliagina approved these changes

2021-06-12 06:45 UTC, kotosha-real requested changes
Хорошая работа!

Оставил несколько комментов, пара правок и всё будет огонь

2021-06-12 06:45 UTC, kotosha-real commented on .editorconfig
> +indent_size = 2
Лишнее, `indent_size` уже задан для всех файлов

2021-06-12 06:45 UTC, kotosha-real commented on .eslintrc.json
>      "plugin:@typescript-eslint/eslint-recommended",
Не применительно к твоим правкам, но на четвёртой строчке в массиве плагинов лишние пробелы

2021-06-12 06:45 UTC, kotosha-real commented on webpack.config.js
> -const production = (process.env.WEBPACK_ENV || process.env.NODE_ENV) === 'production'
Виндаболь)

2021-06-12 06:45 UTC, kotosha-real commented on webpack.config.js
>          use: [ 'style-loader', 'css-loader', 'sass-loader' ],
Тут та же история с пробелами. Если хочется писать так, то надо по всему проекту применить такой стиль, благо он пока небольшой

2021-06-12 06:45 UTC, kotosha-real commented on webpack.config.js
> +    new ESLintPlugin({
Кажется, что это лишнее. У нас есть скрипт `lint` в `package.json`, который делает то же самое и вдогонку запускает stylelint. Сейчас в проекте нет чёткого процесса, по которому тот же stylelint, это довольно просто просыпать. Лучше отказаться от линтеров-плагинов в вебпаке и настроить хуки в репе, которые сделают это за нас, когда мы будет, например, коммитить или пушить какие-то изменения. На этот счёт есть хорошая [статья](https://habr.com/ru/company/ruvds/blog/428173/) на хабре, рекомендую затащить эту штуку сразу

2021-06-12 07:11 UTC, StopNGo commented on webpack.config.js
>          use: [ 'style-loader', 'css-loader', 'sass-loader' ],
В линтере есть правила:
`"object-curly-spacing": ["error", "always"]`
и
```
"array-bracket-spacing": ["error", "always", {
      "singleValue": false,
      "objectsInArrays": false,
      "arraysInArrays": false
    }],
```
так что все ок

2021-06-12 07:14 UTC, StopNGo commented on .editorconfig
> +indent_size = 2
Убрал)

2021-06-12 07:15 UTC, StopNGo commented on webpack.config.js
> +    new ESLintPlugin({
Лучше линтить все сразу по ходу, мне кажеться. Но, согласен, потом можно пре-коммитом обойтись, наверное)
Убрал!

2021-06-12 08:22 UTC, kotosha-real commented on webpack.config.js
>          use: [ 'style-loader', 'css-loader', 'sass-loader' ],
Принял! Кстати, если хотить линтить и конфиг вебпака, то надо добавить `.js` расширение в команду

2021-06-12 08:22 UTC, kotosha-real requested changes
Последний коммент и можно мержить

2021-06-12 08:22 UTC, kotosha-real commented on package.json
> +    "eslint-webpack-plugin": "2.5.4",
Если выпилил, то давай удалим его, чтобы не было неиспользуемых зависимостей

2021-06-12 08:54 UTC, kotosha-real approved these changes
🕵🏻‍♂️

2021-06-12 09:29 UTC, merged