Feature/redux basic
Yandex-SpaceY/SpaceY pull request #21
Opened 2021-06-28 14:24 UTC by StopNGo

Всем привет!
Прикрутил Redux+thunk (thunk - это, конечно, верх изящества, как для отдельного пакета :).
Прикручен также [Redux DevTools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=ru) - если не стоит, то ставьте и отлавливайте лишние дисптачи.
Кроме того, подпилил мое многострадальное меню и игру под работу с глобальным стейтом игры.
Как всегда, жду ваших комментариев!

2021-06-28 16:00 UTC, ValeriaKoliagina commented on src/store/game/actions.tsx
> +  return {
Чтобы не писать везде return, можно написать `=> ({...})`

2021-06-28 16:00 UTC, ValeriaKoliagina commented on src/store/game/actions.tsx
> +  return {
Также чтобы не писать везде export const можно написать типа такого
```
export default {
  setIsGameStarted: (isGameStarted: boolean): TActionProps<string, boolean> => ({
   ...
  }),

  setIsGamePaused: ...
}
```
Но это очень опционально

2021-06-28 16:00 UTC, ValeriaKoliagina commented on src/store/game/reducer.tsx
> += (state = initialState, action: TActionProps<string, TGameState>): Record<string, unknown> => {
Как-то несколько странно выглядит данный перенос... Может
```
export const gameReducer = (
  state = initialState, 
  action: TActionProps<string, TGameState>
 ): Record<string, unknown> => {
```
?

2021-06-28 16:00 UTC, ValeriaKoliagina commented on src/store/store.tsx
> +      : (f: () => void) => f
Не очень понимаю этот момент...

2021-06-28 23:43 UTC, StopNGo commented on src/store/store.tsx
> +      : (f: () => void) => f
Как-то так
https://medium.com/@e_himmelfarb/implement-redux-devtools-extension-with-thunk-and-other-async-middleware-20e97100b2b0

2021-06-29 06:53 UTC, StopNGo commented on src/store/game/actions.tsx
> +  return {
Подскажи, а как делать такой массовый экспорт, но не default. У меня как-то не получатся. 
Во-первых как-то слишком много default экспортов получается.
Во-вторых - часто встречаю много доводов не использовать default экспорті вообще. Даже тут есть - https://learn.javascript.ru/import-export#dovod-protiv-eksportov-po-umolchaniyu

2021-06-29 21:25 UTC, ValeriaKoliagina approved these changes

2021-06-30 10:35 UTC, SupergroverNN approved these changes

2021-06-30 13:38 UTC, kotosha-real requested changes
Здорово, хорошая работа!
Комменты внутри + переименуй, пожалуйста, файлы, которые не содержат в себе JSX-разметки `.tsx => .ts`

2021-06-30 13:38 UTC, kotosha-real commented on src/store/types.d.ts
> +  user: TUserState;
🧐
Когда читаешь код и видишь какое-то объявление, хочется поискать его выше. Поэтому сначала лучше объявлять "обычные" типы, а потом те, которые используют ранее объявленные типы в качестве своих полей

2021-06-30 13:38 UTC, kotosha-real commented on src/store/types.d.ts
> +  : ReduxAction<T> & Readonly<{ payload: P }>;
❓
Поправь, если я не прав, но тут кажется можно проще получить схожее, нет?
```suggestion
export type TActionProps<T = string, P = unknown> = ReduxAction<T> & Readonly<{ payload: P }>;
```

2021-06-30 13:38 UTC, kotosha-real commented on src/store/user/reducer.tsx
> +      return { ...state, error: action.payload };
❗️
Давай добавим поле `error: null` в `initialState`

2021-06-30 13:38 UTC, kotosha-real commented on src/store/user/actions.tsx
> +      dispatch(setUserData(data.data));
❗️
У нас сейчас ошибка нигде не очищается, и это довольно плохо. Представь ситуацию: первый запрос падает, ui на это реагирует, юзер повторно шлёт запрос, на этот раз всё взлетает, но `error` всё ещё содержит в себе ошибку

2021-06-30 13:38 UTC, kotosha-real commented on src/store/game/reducer.tsx
> +
❗️
```suggestion
```

2021-06-30 13:38 UTC, kotosha-real commented on src/store/types.d.ts
> +  error?: Error;
❗️
В одном из комментов найдёшь аргументацию почему лучше так)
```suggestion
  error: Error | null;
```

2021-06-30 13:38 UTC, kotosha-real commented on src/store/types.d.ts
> +  phone: string;
🧐
По-хорошему, на фронте надо обходиться без снейк кейса. Потом (в идеале в nice-to-have колонку положить) будет здорово написать миддлвару для форматирования данных в серверном виде к фронтовому (читай, к кэмел кейсу)

2021-06-30 13:38 UTC, kotosha-real commented on src/store/constants.tsx
> +export enum USER_ACTIONS {
❗️
Я не уверен, что это должно быть тут. У нас есть отдельные константы под неймспейсом, лучше туда запихать в отдельный файл

2021-06-30 13:38 UTC, kotosha-real commented on src/components/gameCanvas/GameCanvas.tsx
> +    dispatch(setIsGameStarted(isGameSatrted));
❗️
```suggestion
  const setIsGameStartedStatus = (isGameStarted: boolean) => {
    dispatch(setIsGameStarted(isGameStarted));
```

2021-06-30 13:38 UTC, kotosha-real commented on src/game/gamemain.ts
> +    setGamePauseStatus: (isGamePaused: boolean) => void
🧐
Красиво было бы передавать объект вместо кучи аргументов:
1. Сложнее ошибиться
2. Сложнее перепутать порядок

Это можно юзать как правило: больше 4-5 аргументов, значит, их стоит передавать в одном объекте

2021-07-01 20:20 UTC, StopNGo commented on src/store/types.d.ts
> +  phone: string;
Пока оставил как есть. Но вопрос - а как именно это должно работать? Не в рантайме же ресурсы еще и на это тратить. Мож какой веб-пак плагин?

2021-07-01 20:22 UTC, StopNGo commented on src/game/gamemain.ts
> +    setGamePauseStatus: (isGamePaused: boolean) => void
Тут я переделаю уже при рефакторинге.

2021-07-01 20:34 UTC, kotosha-real commented on src/store/types.d.ts
> +  phone: string;
Это же апишка, она в рантайме будет данные отдавать)
Там довольно простой пайплайн:
1. Типизируются ответы апи
2. Придумывается фронтовая структура и тоже типизируется
3. Добавляется мидлварь для форматирования, которая из апишного формата переводит во фронтовый и наоборот
4. Клиент работает уже с нужной структурой, апишка (когда шлёшь данные, а не просто получаешь) — тоже

Ресурсов там капля)
Пробежался по ключам, отформатировал и отдал

2021-07-01 20:46 UTC, kotosha-real approved these changes
🕵🏻‍♂️
Огонь!
В одном месте не убрал лишнюю пустую строку. После выпила можно мержить)

2021-07-01 20:46 UTC, kotosha-real commented on src/store/user/reducer.ts
> +
❗️
Не убрал)

2021-07-01 20:46 UTC, kotosha-real commented on src/store/user/actions.ts
> +import { ThunkAction } from 'redux-thunk';
🧐
Править не нужно, но есть такой подход, когда импорты сортируются по определённым правилам. Сейчас на рабочем проекте, например, порядок такой:
1. Внешние пакеты (которые в `node_modules`)
2. Вся внутрянка: компоненты, утилиты, константы, хелперы
3. Стили

Всё внутри своего блока сортируется по алфавиту, каждый блок отбивается пустой строкой.
Казалось бы, что совершенно необязательная вещь, но по факту даже это делает код читабельнее и субъективно красивее)

2021-07-01 20:46 UTC, kotosha-real commented on src/store/user/actions.ts
> +      dispatch(setUserError(null));
👍🏻

2021-07-01 21:02 UTC, merged

2021-07-01 21:04 UTC, StopNGo commented on src/store/user/reducer.ts
> +
Таки придется перейти на использования готового набора правил линтера)))