feat: add testing
Yandex-SpaceY/SpaceY pull request #25
Opened 2021-07-05 09:36 UTC by SupergroverNN

Добавил тестирование компонентов снапшотами.
Пока не добавил прекоммит, сделаю вечером вместе с тем что накидается в комментах(может, пока рабочий день идет кто-то успеет посмотреть).

2021-07-05 09:42 UTC, ValeriaKoliagina commented on src/components/input/input.test.tsx
> +  expect(component.text()).toEqual('testTitle');
Я, если честно, не уверена, что есть смысл проверять пропсы. Ведь сам реакт это уже проверил...

2021-07-05 10:21 UTC, SupergroverNN commented on src/components/input/input.test.tsx
> +  expect(component.text()).toEqual('testTitle');
Я думал, что тесты нужны на случай "изменил что-то и оно перестало работать так, как работало до этого". Это начало тестирования с проверкой того, что все что передалось, появится там где ожидалось.

2021-07-05 20:06 UTC, ValeriaKoliagina approved these changes

2021-07-06 20:24 UTC, StopNGo approved these changes

2021-07-07 05:54 UTC, kotosha-real commented
@SupergroverNN привет!
Почини конфликты, потом я посмотрю

2021-07-07 18:53 UTC, kotosha-real requested changes
Здорово!
Хочется чуть больше покрытия, я указал примерные варианты для кнопки и `ErrorBoundary`. Для остальных компонентов тоже стоит предусмотреть все возможные варианты

2021-07-07 18:53 UTC, kotosha-real commented on src/components/button/button.test.tsx
> +});
❗️
Давай добавим чуть больше покрытия, например:
1. Кнопка без `children`
2. Кнопка с типом
3. Кнопка получила `onclick` проп

Последнее можно получить как-то так (в примере юзается `react-test-renderer`):
```
test('Use handleClick prop', () => {
    const foo = () => {}
    const component = renderer
      .create(<Button buttonText="Oh hi" handleClick={foo} />)
      .toJSON()
    expect(component.props.onClick).toEqual(foo)
    expect(component).toMatchSnapshot()
  })
```

2021-07-07 18:53 UTC, kotosha-real commented on src/components/errorBoundary/errorBoundary.test.tsx
> +});
❗️
Аналогично тут. Нужно проверить, что при наличии ошибки внутри, `ErrorBoundary` покажет заглушку. Для этого можно сделать мок-компонент `Throwable`, который будет кидать эксепшн, типа такого:
```
export const Throwable: React.FC = (): never => {
  throw new Error('Oops...')
}
```

2021-07-07 18:53 UTC, kotosha-real commented on src/components/input/input.test.tsx
> +it('check render component Input', () => {
❗️
Тут аналогично кнопке

2021-07-07 18:53 UTC, kotosha-real commented on webpack.config.js
> +    extensions: ['.tsx', '.ts', '.js', '.scss'],
❗️
Кажется, что эти отступы убираться не должны

2021-07-07 18:53 UTC, kotosha-real commented on webpack.config.js
> +        use: ['style-loader', 'css-loader', 'sass-loader'],
❗️
Аналогично

2021-07-07 18:53 UTC, kotosha-real commented on src/constants/commonConstants.ts
>  export const BASE_URL = 'https://ya-praktikum.tech/api/v2/';
❓
А как же `insert_final_newline = true` в `.editorconfig`?

2021-07-09 16:54 UTC, kotosha-real approved these changes
🕵🏻‍♂️
Молодец!
Аппрувлю, но давай учтём комменты)

2021-07-09 16:54 UTC, kotosha-real commented on src/components/errorBoundary/errorBoundary.test.tsx
> +    console.log(component.debug());
❗️
Логи не коммитим)

2021-07-09 16:54 UTC, kotosha-real commented on src/components/errorBoundary/errorBoundary.test.tsx
> +});
❗️
```suggestion
  });
});
```

2021-07-09 16:54 UTC, kotosha-real commented on src/components/errorBoundary/errorBoundary.test.tsx
> +    const component = shallow(<ErrorBoundary>{Throwable}</ErrorBoundary>);
❗️
```suggestion
    const component = shallow(<ErrorBoundary><Throwable /></ErrorBoundary>);
```

2021-07-09 16:54 UTC, kotosha-real commented on src/components/errorBoundary/errorBoundary.test.tsx
> +  it('check render w/o error', () => {
❗️
```suggestion
describe('test ErrorBoundary', () => {
  it('check render w/o error', () => {
```

2021-07-09 16:54 UTC, kotosha-real commented on src/components/input/input.test.tsx
> +    expect(component).toMatchSnapshot();
❗️
Давай пройдёмся по коду и подровняем всё: консты к констам, экспекты к экспектам. Должно как-то так получиться
```suggestion
    const component = shallow(<Input
      value='testValue'
      name='testName'
      title='testTitle'
    />);
    const whatever = 1;
    
    expect(component.text()).toEqual('testTitle');
    expect(component).toMatchSnapshot();
```

2021-07-09 16:54 UTC, kotosha-real commented on src/components/input/input.test.tsx
> +  it('check render component with title', () => {
❓
Не первый раз вижу, спецом так пишешь? Если это часть код стайла, то можно оставить, просто интересно почему

2021-07-09 16:54 UTC, kotosha-real commented on src/components/input/input.test.tsx
> +    expect(component.find('input').get(0).props.type).toEqual('password');
❗️
Достоинство снапшотных тестов, что тут не нужны такие дословные проверки. Если посмотреть на получившийся снапшот, то там отпечатался тип, и если ты потом его уберёшь в компоненте и запустишь тест повторно, то он упадёт
```suggestion
```

2021-07-09 17:40 UTC, SupergroverNN commented on src/components/input/input.test.tsx
> +  it('check render component with title', () => {
я, руководствуясь тем что между всеми группами пустые строки, так написал и в тестах)
пусть будет без лишних строк)

2021-07-09 17:41 UTC, SupergroverNN commented on src/components/input/input.test.tsx
> +    expect(component.find('input').get(0).props.type).toEqual('password');
понятно, что это не влияет на снапшоты, это зачатки неснапшотного тестирования =)

2021-07-09 17:51 UTC, SupergroverNN commented on src/components/errorBoundary/errorBoundary.test.tsx
> +    console.log(component.debug());
fixed

2021-07-09 17:51 UTC, SupergroverNN commented on src/components/errorBoundary/errorBoundary.test.tsx
> +});
fixed

2021-07-09 17:51 UTC, SupergroverNN commented on src/components/errorBoundary/errorBoundary.test.tsx
> +    const component = shallow(<ErrorBoundary>{Throwable}</ErrorBoundary>);
fixed

2021-07-09 17:51 UTC, SupergroverNN commented on src/components/errorBoundary/errorBoundary.test.tsx
> +  it('check render w/o error', () => {
fixed

2021-07-09 18:02 UTC, SupergroverNN commented on src/components/input/input.test.tsx
> +    expect(component).toMatchSnapshot();
fixed

2021-07-09 18:02 UTC, SupergroverNN commented on src/components/input/input.test.tsx
> +  it('check render component with title', () => {
fixed

2021-07-09 18:05 UTC, SupergroverNN commented on src/components/input/input.test.tsx
> +    expect(component.find('input').get(0).props.type).toEqual('password');
fixed

2021-07-09 18:19 UTC, merged