Router added
Yandex-SpaceY/SpaceY pull request #3
Opened 2021-06-12 15:23 UTC by ValeriaKoliagina

2021-06-12 15:45 UTC, SupergroverNN approved these changes

2021-06-13 08:59 UTC, kotosha-real requested changes
Хорошая работа!

Посмотри комментарии, опечатку в `jsconfig.json` надо поправить и про пустую страницу ответить, остальное на твоё усмотрение

2021-06-13 08:59 UTC, kotosha-real commented on jsconfig.json
> +      "constnats/*": ["./src/constants/*"],
Очепятка)

2021-06-13 08:59 UTC, kotosha-real commented on src/pages/index.ts
> +import Dashboard from 'pages/dashboard/Dashboard';
Индексы директорий — хорошая практика, молодец)
Но тут можно сократить и писать, например, `export { default as Dashboard } from 'pages/dashboard/Dashboard';`

2021-06-13 08:59 UTC, kotosha-real commented on src/router/Router.tsx
> +import { Dashboard, Forum, Game, Leaderboard, Login, NotFound, Profile, ProfileEdit, Signup } from 'pages';
Обычно, когда импортируемых сущностей так много, то их независимо от длины строки лучше писать с новой строки. Опциональный комментарий, смотри сама как больше нравится)

2021-06-13 08:59 UTC, kotosha-real commented on src/pages/EmptyPageForRouter.tsx
> +import React from 'react';
В этой странице есть смысл? Она никуда не импортируется и нигде больше не юзается

2021-06-13 08:59 UTC, kotosha-real commented on src/pages/forum/Forum.tsx
> +  <>
Понятно, что заглушка, но фрагмент лишний

2021-06-13 12:03 UTC, ValeriaKoliagina commented on jsconfig.json
> +      "constnats/*": ["./src/constants/*"],
Спасибо)

2021-06-13 12:03 UTC, ValeriaKoliagina commented on src/pages/index.ts
> +import Dashboard from 'pages/dashboard/Dashboard';
Поправила, спасибо

2021-06-13 12:03 UTC, ValeriaKoliagina commented on src/router/Router.tsx
> +import { Dashboard, Forum, Game, Leaderboard, Login, NotFound, Profile, ProfileEdit, Signup } from 'pages';
Согласна, поправила

2021-06-13 12:04 UTC, ValeriaKoliagina commented on src/pages/EmptyPageForRouter.tsx
> +import React from 'react';
Нет, нету. Я ее использовала как первоначальную заглушку, а потом просто забыла удалить. Удалила

2021-06-13 12:04 UTC, ValeriaKoliagina commented on src/pages/forum/Forum.tsx
> +  <>
Поправила, спасибо

2021-06-13 14:14 UTC, kotosha-real approved these changes
🕵🏻‍♂️

2021-06-13 14:27 UTC, merged