feat: add vibration API and make it optionality
Yandex-SpaceY/SpaceY pull request #38
Opened 2021-07-22 22:06 UTC by SupergroverNN

Добавление режима вибрации (протестировано на телефоне)

2021-07-23 08:19 UTC, ValeriaKoliagina commented on src/game/GameMain.ts
> +          if (current === this.col) {
Поясни, пожалуйста, этот момент. Я не очень понимаю, мы сначала присвоили, а потом проверяем что они равны. Наверное, я что-то упускаю)

2021-07-23 08:21 UTC, ValeriaKoliagina commented on package.json
> +    "start": "cross-env NODE_ENV=development webpack serve --mode development --open --hot --host 0.0.0.0",
![image](https://user-images.githubusercontent.com/32342424/126755616-66521569-bdfd-48c0-8621-8d5dad7ebdc0.png)

2021-07-23 08:46 UTC, SupergroverNN commented on src/game/GameMain.ts
> +          if (current === this.col) {
мы сначала присвоили, но через полсекунды(когда сетТаймаут вызовет проверку), значение может измениться) 
если через пол секунды оно другое, значит вибрацию не останавливаем, если оно такое же, стопорим ее )

2021-07-23 08:50 UTC, SupergroverNN commented on package.json
> +    "start": "cross-env NODE_ENV=development webpack serve --mode development --open --hot --host 0.0.0.0",
шож такое то =( в целом, я делал это для того, чтобы проверить на телефоне вибрацию, может для винды как то по другому надо это запускать.
<img width="1259" alt="Screenshot 2021-07-23 at 11 48 12" src="https://user-images.githubusercontent.com/40541530/126758739-018d87e1-1027-423b-b818-fe8287c6a973.png">

2021-07-23 08:54 UTC, SupergroverNN commented on package.json
> +    "start": "cross-env NODE_ENV=development webpack serve --mode development --open --hot --host 0.0.0.0",
на виндовом ноуте не работает =( будут фиксить

2021-07-23 08:57 UTC, SupergroverNN commented on package.json
> +    "start": "cross-env NODE_ENV=development webpack serve --mode development --open --hot --host 0.0.0.0",
fixed

2021-07-23 08:58 UTC, SupergroverNN commented on package.json
> +    "start": "cross-env NODE_ENV=development webpack serve --mode development --open --hot --host 0.0.0.0",
винда не понимает 0.0.0.0 но понимает 127.0.0.1, мак его тоже понимает потому это оказалось решением проблем)

2021-07-23 09:25 UTC, SupergroverNN commented on package.json
> +    "start": "cross-env NODE_ENV=development webpack serve --mode development --open --hot --host 0.0.0.0",
все, хост убирается.

2021-07-23 09:30 UTC, StopNGo commented on src/game/GameMain.ts
> +
Привет! может саму работу с Vibration API вынести в отдельный core модуль? Как-то не логично эти методы смотрятся в GaimMain

2021-07-23 09:41 UTC, ValeriaKoliagina commented on src/components/menu/menu.scss
> +      width: 74px;
я бы может объединила их общие стили, 
```
.true, .false {
     display: inline-block;
      width: 74px;
 }
```

2021-07-23 09:50 UTC, SupergroverNN commented on src/components/menu/menu.scss
> +      width: 74px;
fixed

2021-07-23 09:55 UTC, ValeriaKoliagina approved these changes

2021-07-24 06:27 UTC, kotosha-real requested changes
Хорошая работа!
Оставил несколько комментов, надо немного доработать пр перед аппрувом, например, переписать хелпер для получения статуса элемента меню

2021-07-24 06:27 UTC, kotosha-real commented on src/components/gameCanvas/GameCanvas.tsx
> +  const isVibrationOn = useSelector(gameIsVibrationOnSelector);
❗️
Ты юзаешь этот же селектор в `Game`, давай сюда спустим пропсой. Со звуком аналогично

2021-07-24 06:27 UTC, kotosha-real commented on src/components/gameCanvas/GameCanvas.tsx
> +  }, []);
❗️
Лишнее, по сути таким образом одна строчка кода, которая сама себя хорошо документирует, оборачивается в другую функцию + хук. Давай вынесем `gameMain.setVibrationStatus(status)` туда, где сейчас юзается обёртка. В целом `useCallback` стоит использовать, когда мы хотим функцию передать пропсой вниз — это спасёт от лишних ререндеров. В нашем случае смысла от использования нет)

2021-07-24 06:27 UTC, kotosha-real commented on src/components/gameCanvas/GameCanvas.tsx
> +      <canvas ref={canvasRef} className={cn('game-canvas', className)} width={GAME_OPTIONS.CANVAS_WIDTH} height={GAME_OPTIONS.CANVAS_HEIGHT} />
👍🏻

2021-07-24 06:27 UTC, kotosha-real commented on src/constants/commonConstants.ts
> +export const ON_OFF_ITEMS = {
🧐
Мб свитч или тоггл?)

2021-07-24 06:27 UTC, kotosha-real commented on src/game/GameMain.ts
> +
❗️
@StopNGo дело говорит. Давай сделаем отдельный модуль под вибрацию, заюзаем в качестве поля `GameMain (скажем, `vibrationController`) и тут будем дёргать его методы, обращаясь к нему

2021-07-24 06:27 UTC, kotosha-real commented on src/components/menu/Menu.tsx
> +  };
❗️
Не DRY + классы `true`/`false` называть не стоит. Предлагаю такой рефакторинг:
```suggestion
  const getMenuItemMode = (title: string): ReactElement | null => {
    switch (title) {
      case 'sound:':
      case 'vibration:': {
        const pureTitle = title.substring(0, title.length - 1);
        const mode = modifiers[pureTitle] ? 'ON' : 'OFF';

        return <span className={`menu-item_mode_${mode}`}>{ON_OFF_ITEMS[mode]}</span>;
      }
      default: return null;
    }
  };
```

Какие плюсы:
1. Нет дубляжа кода
2. Сложность не изменилась

Какие минусы:
1. Надо отрефакторить способ передачи `modifier`-ов
2. `title` содержит в себе двоеточие и его надо чистить, выглядит костыльно
3. Это всё ещё не оптимально. Лучше всего было бы получать тип элемента меню в момент вывода и, если подразумеваем чистый `title`, то в хелпере не было бы необходимости: если тип элемента `mode` (имя можно взять любое), то из объекта `modifier`-ов доставался бы его статус и выводился. Было бы максимально чисто и красиво

Если есть другие идеи как избавиться от дубляжа, то можно заюзать их, но в таком виде не катим

@StopNGo FYI, мб настало время чуть-чуть порефачить меню

2021-07-24 06:27 UTC, kotosha-real commented on src/components/menu/Menu.tsx
> +                  {title} {getMenuItem(title)}
🧐
В идеале не выводить кнопку с вибрацией на десктопе, но это пока nice-to-have

2021-07-24 18:54 UTC, SupergroverNN commented on src/constants/commonConstants.ts
> +export const ON_OFF_ITEMS = {
у меня был такой же ход мыслей, но подумал что тоггл это можеть быть и тру/фолс и свитч тоже, а тут немного режет глаза, но умнее ничего не придумалось))

2021-07-24 18:57 UTC, SupergroverNN commented on src/components/menu/Menu.tsx
> +  };
соглашусь, что выглядит это стремно, еще не весь разум ко мне вернулся после недуга)))
пофикшу!

2021-07-24 19:38 UTC, SupergroverNN commented on src/components/gameCanvas/GameCanvas.tsx
> +  const isVibrationOn = useSelector(gameIsVibrationOnSelector);
fixed

2021-07-24 19:46 UTC, SupergroverNN commented on src/components/gameCanvas/GameCanvas.tsx
> +  }, []);
fixed

2021-07-24 20:33 UTC, SupergroverNN commented on src/components/menu/Menu.tsx
> +  };
fixed (надеюсь)

2021-07-24 20:34 UTC, SupergroverNN commented on src/constants/commonConstants.ts
> +export const ON_OFF_ITEMS = {
fixed

2021-07-24 21:20 UTC, SupergroverNN commented on src/components/menu/Menu.tsx
> +                  {title} {getMenuItem(title)}
fixed

2021-07-25 00:20 UTC, SupergroverNN commented
меню тоже запилилось

2021-07-25 00:49 UTC, SupergroverNN commented on src/game/GameMain.ts
> +
fixed

2021-07-25 11:27 UTC, StopNGo approved these changes
Привет! Спасибо, что взялся за эти задачи, включая меню)
Аппрув, но есть один момент с index.ts в core и названия модуля вибрации.
Ну а по isTest, наверное по-другому никак, просто спросил Антона, как лучше в таких случаях.

2021-07-25 11:27 UTC, StopNGo commented on src/game/GameMain.ts
> +import  VibrationController from 'game/core/vibrationController/VibrationController';
1. В core есть index.ts
2. Может лучше уже сохранить стиль коротrих названий в core и оставить просто Vibration?

2021-07-25 11:27 UTC, StopNGo commented on src/components/menu/Menu.tsx
> +  isTest?: boolean;
а isTest исключительно для тестов?
@kotosha-real Это норм практика или все же как-то по-другому решают? просто интересно)

2021-07-25 11:35 UTC, kotosha-real approved these changes
🕵🏻‍♂️
Ещё пак комментов и можно мержиться)

2021-07-25 11:35 UTC, kotosha-real commented on src/game/core/vibrationController/VibrationController.ts
> +  startVibrate(duration: number[]): void {
🧐
```suggestion
  startVibration(duration: number[]): void {
```

Или просто `vibrate` было бы ближе к делу, но это уже мелочи

2021-07-25 11:35 UTC, kotosha-real commented on src/game/GameMain.ts
> +  vibration: VibrationController;
❗️
Лучше тоже назвать `vibrationController`, иначе с ходу непонятно, что это отдельный модуль

2021-07-25 11:35 UTC, kotosha-real commented on src/game/GameMain.ts
> +import  VibrationController from 'game/core/vibrationController/VibrationController';
❗️
```suggestion
import VibrationController from 'game/core/vibrationController/VibrationController';
```

2021-07-25 11:35 UTC, kotosha-real commented on src/constants/menuConstants.ts
> +  { title: 'vibration', isWithModifier: true, isMobileOnly: true, route: null, action: MENU_ACTIONS.GAME_VIBRATION_SWITCH },
🧐
```suggestion
  { title: 'vibration', withModifier: true, mobileOnly: true, route: null, action: MENU_ACTIONS.GAME_VIBRATION_SWITCH },
```
`if (item.withModifier) ...` звучит чуть лучше, чем `if (item.isWithModifier) ...`

2021-07-25 11:35 UTC, kotosha-real commented on src/components/menu/Menu.tsx
> +  if (!isTest && window) {
❗️
```suggestion
  let isMobile = false;
  
  if (!isTest && window) {
```

В идеале это отдельным хуком сделать

2021-07-25 11:35 UTC, kotosha-real commented on src/components/menu/Menu.tsx
> +        && <h1>{GAME_NAME}</h1>
❗️
Тут можно в одну строку уместить)

2021-07-25 11:35 UTC, kotosha-real commented on src/components/menu/Menu.tsx
> +          menuItems.map(({ title, route, action, isMobileOnly, isWithModifier }) => {
🧐
Тут просится создать отдельный компонент `MenuItem`. Закинь в nice-to-have, сейчас не будем на него тормозиться

2021-07-25 11:35 UTC, kotosha-real commented on src/components/menu/Menu.tsx
>              const callback = () => {
❗️
```suggestion
            if (isMobileOnly && !isMobile) {
              return;
            }
            
            const callback = () => {
```

2021-07-25 11:35 UTC, kotosha-real commented on src/components/menu/Menu.tsx
> +                    && <span className={`menu-item_mode_${mode.toLowerCase()}`}>{TOGGLE_ITEMS[mode]}</span>
🧐
```suggestion
                  {isWithModifier && (
                  <span className={`menu-item_mode_${mode.toLowerCase()}`}>{TOGGLE_ITEMS[mode]}</span>
                  )
```

2021-07-25 11:35 UTC, kotosha-real commented on src/components/menu/Menu.tsx
> +                  {`${title}${isWithModifier ? ':' : ''}`}
👍🏻

2021-07-25 11:35 UTC, kotosha-real commented on src/components/gameCanvas/GameCanvas.tsx
> +  }, []);
Хорошо, давай потом вернёмся к этому моменту, чтобы сейчас двинуться дальше

2021-07-25 11:46 UTC, SupergroverNN commented on src/game/GameMain.ts
> +import  VibrationController from 'game/core/vibrationController/VibrationController';
fixed )

2021-07-25 11:47 UTC, SupergroverNN commented on src/components/menu/Menu.tsx
> +  isTest?: boolean;
isTest только для теста, в теории, можно подключить для тестов jsdom и тогда isTest будет не нужен

2021-07-25 11:49 UTC, SupergroverNN commented on src/game/core/vibrationController/VibrationController.ts
> +  startVibrate(duration: number[]): void {
названия функций как и они сами были взяты из доки к апи, отсюда и названия )

2021-07-25 11:49 UTC, SupergroverNN commented on src/game/core/vibrationController/VibrationController.ts
> +  startVibrate(duration: number[]): void {
fixed

2021-07-25 11:50 UTC, SupergroverNN commented on src/game/GameMain.ts
> +  vibration: VibrationController;
fixed

2021-07-25 11:50 UTC, SupergroverNN commented on src/game/GameMain.ts
> +import  VibrationController from 'game/core/vibrationController/VibrationController';
fixed

2021-07-25 11:51 UTC, SupergroverNN commented on src/constants/menuConstants.ts
> +  { title: 'vibration', isWithModifier: true, isMobileOnly: true, route: null, action: MENU_ACTIONS.GAME_VIBRATION_SWITCH },
ту была дилема, направшивалось withModifier, но булеан переменные мы же договорились называть начиная с is?

2021-07-25 11:52 UTC, SupergroverNN commented on src/components/menu/Menu.tsx
>              const callback = () => {
fixed

2021-07-25 11:53 UTC, SupergroverNN commented on src/components/menu/Menu.tsx
> +                    && <span className={`menu-item_mode_${mode.toLowerCase()}`}>{TOGGLE_ITEMS[mode]}</span>
линтер сказал что && должен быть на следующей строке, я его послушал(

2021-07-25 11:55 UTC, SupergroverNN commented on src/components/menu/Menu.tsx
> +          menuItems.map(({ title, route, action, isMobileOnly, isWithModifier }) => {
добавлена задача в трелло

2021-07-25 11:55 UTC, SupergroverNN commented on src/components/menu/Menu.tsx
> +  if (!isTest && window) {
вообще все эти отступы, наверное в идеале, настраиваются в преттире/еслинте ?

2021-07-25 11:56 UTC, SupergroverNN commented on src/constants/menuConstants.ts
> +  { title: 'vibration', isWithModifier: true, isMobileOnly: true, route: null, action: MENU_ACTIONS.GAME_VIBRATION_SWITCH },
хотя это не переменная тут наверное а больше как параметр

2021-07-25 11:58 UTC, SupergroverNN commented on src/constants/menuConstants.ts
> +  { title: 'vibration', isWithModifier: true, isMobileOnly: true, route: null, action: MENU_ACTIONS.GAME_VIBRATION_SWITCH },
fixed

2021-07-25 12:02 UTC, SupergroverNN commented on src/components/menu/Menu.tsx
> +        && <h1>{GAME_NAME}</h1>
fixed

2021-07-25 12:02 UTC, merged