Pages components
Yandex-SpaceY/SpaceY pull request #5
Opened 2021-06-13 17:27 UTC by SupergroverNN

2021-06-13 17:59 UTC, ValeriaKoliagina commented on package.json
> +    "prettier": "^2.3.1",
Установи, пожалуйста, конкретные версии. Также не очень понятно, зачем нам еще и преттир

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/components/button/Button.tsx
> +import './button.scss';
А давай разделять внешние и внутренние импорты пустой строкой, для большей наглядности)

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/components/button/Button.tsx
> +export default Button;
Не забывай о пустой строке, пожалуйста

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/components/button/Button.tsx
> +    <button className="one-button" onClick={onClick}>{text}</button>
Было бы неплохо иметь возможность передачи класса из родителя, если понадобится переопределять в каком-то компоненте стили. Также у тебя кнопка принимает только текст, а если у нас будет кнопка со стрелкой в ней (наподобие назад)?

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/components/button/button.scss
> +  background-color: #36535b;
Было бы неплохо вынести цвета в отдельный файл, наподобие `@primary-color: #36535b` и использовать по всему приложению. Также сделать и с остальными основными вещами. Также было бы неплохо, если бы кнопка знала что-то о своем состоянии, я имею в виду добавить стили для ховер, фокус, эктив.

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/components/input/Input.tsx
> +      <span className="title">{title}</span>
Может ли быть такая ситуация, что инпут у нас будет без лэйбла? Если да, то твой вариант не подойдет. Так же не совсем понятно, почему это спан, а не` label`, который через id связан с инпутом

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/components/input/Input.tsx
> +      <span className="error-message">{errorText}</span>
Стоит ли нам всегда рисовать место под ошибку, если этой ошибки может и не быть? (например в профиле)

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/components/input/Input.tsx
> +      <input className="input" onChange={onChange} name={name} type={type} />
А как же плейсхолдер?

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/components/input/input.scss
> +  &.error {
Не очень понятно, где это используется... И про стили то же самое, что и в кнопках

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/index.tsx
> +import Login from 'pages/login/Login';
Зачем тут менять было???

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/pages/login/Login.tsx
> +import { fakeOnChange, fakeOnClick } from 'utils';
Можно использовать алиасы, также предлагаю стили импортить в самом низу (так как они лежат ближе всего к компоненту)

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/pages/login/Login.tsx
> +        <h1>SpaceY</h1>
Если это текст, который мы оставляем, вынеси его, пожалуйста, в константы. Аналогично для всех текстовых нод

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/pages/login/Login.tsx
> +    <div className="main login">
А почему ты не используешь форму?

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/pages/login/Login.tsx
> +          <Link to="/signup" className="link">
Думаю, стоило бы создать компонент Link, который мы потом могли использовать с одинаковыми стилями

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/pages/login/Login.tsx
> +            Has no Pilot ID?
Что такое Pilot ID?

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/pages/menu/Menu.tsx
> +import './menu.scss';
Предлагаю сначала внешние зависимости импортить, потом через пустую линию внутренние, стили в самом низу

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/pages/menu/Menu.tsx
> +    <div className="menu">
Форма?

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/pages/menu/Menu.tsx
> +        <h1>SpaceY</h1>
Текстовые ноды тут и в строке 22

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/pages/menu/Menu.tsx
> +            const key = `${i}-${item.title}`;
Если title - это уникальное имя, то индект лучше не использовать, так как при удалении одного названия будет перерисовано все дерево (а не только те, что изменились)

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/pages/menu/menu.scss
> +  .menu-item {
Можно ли тут использовать след синтаксис? вместо `.menu-item` `?-item`. Если можно - то мне кажется, было бы неплохо использовать такой подход, чтобы сразу видеть что от чего зависит и писать меньше кода

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/pages/menu/menu.scss
> +}
Если честно, не очень вижу преимущество scss. Потому что подход используется тот же, что и при обычном css...

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/pages/profile/Profile.tsx
> +import Button from '../../components/button/Button';
Тут также можно использовать алиасы

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/pages/profile/Profile.tsx
> +    <div className="main">
Форма? текстовые ноды?

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/pages/signup/Signup.tsx
> +    <div className="main">
Форма? Ноды?

2021-06-13 17:59 UTC, ValeriaKoliagina commented on src/pages/signup/Signup.tsx
> +        <h1>SpaceY</h1>
Мне кажется, или на всех страницах рисуется один и тот же Space Y? Можно есть смысл создать для него отдельную штуку (например в папке sharedComponents) и использовать его?

2021-06-13 18:09 UTC, SupergroverNN commented on package.json
> +    "prettier": "^2.3.1",
fixed

2021-06-13 18:11 UTC, SupergroverNN commented on src/components/button/Button.tsx
> +import './button.scss';
ок, fixed

2021-06-13 18:15 UTC, SupergroverNN commented on src/components/button/Button.tsx
> +    <button className="one-button" onClick={onClick}>{text}</button>
я думал про классы, но на данном этапе не возникло потребности в дополнительных свойствах, поэтому я их не добавлял, решив, что "прокачивать" инпут и кнопку можно будет по мере возникновения проблем.

2021-06-13 18:16 UTC, SupergroverNN commented on src/components/button/Button.tsx
> +export default Button;
fixed

2021-06-13 18:45 UTC, SupergroverNN commented on src/components/input/Input.tsx
> +      <input className="input" onChange={onChange} name={name} type={type} />
fixed

2021-06-13 18:50 UTC, SupergroverNN commented on src/components/input/Input.tsx
> +      <span className="error-message">{errorText}</span>
Для предотвращения деформации формы, блок с ней висит всегда (иначе можно было бы скрывать этот блок при отсутствия текста ошибки), иначе при возникновении на каком либо из инпутов ошибки, под ним будет больше отступ чем под другими. В профиле, наверное, предполагается редактирование данных (где при нажатии кнопки редактирования данных, инпуты перейдут в состояние редактирования), а тогда отображение блока с ошибкой актуально.

2021-06-13 18:54 UTC, SupergroverNN commented on src/components/input/input.scss
> +  &.error {
пока не используется класс error, потому что нет валидации. Можно удалить это и вставить, когда она появится. Реализация инпута была взята из предыдущего модуля и там это использовалось.

2021-06-13 18:54 UTC, ValeriaKoliagina commented on src/components/input/Input.tsx
> +      <span className="error-message">{errorText}</span>
Ок, просто можно было бы передавать дополнительно пропсу isForm, к примеру, и если она передана, то этот спан рисовать, а если нет, то не рисовать (к примеру, если понадобится добавить поиск)

2021-06-13 18:56 UTC, SupergroverNN commented on src/index.tsx
> +import Login from 'pages/login/Login';
пока не было роутинга, я верстал путем замены использования вместо app верстаемого компонента. При мерже конфликтов не возникло и моя версия файла, видимо оказалась приоритетнее.. Исправил.

2021-06-13 18:59 UTC, SupergroverNN commented on src/pages/login/Login.tsx
> +import { fakeOnChange, fakeOnClick } from 'utils';
fixed. Насчет расположения импортов в зависимости от близости к компоненту - интересная тема)
вообще вроде есть библиотека, которая сортирует импорты и делает между категориями импортов отступы.

2021-06-13 19:03 UTC, SupergroverNN commented on src/pages/login/Login.tsx
> +    <div className="main login">
Действительно..)

2021-06-13 19:09 UTC, SupergroverNN commented on src/pages/login/Login.tsx
> +    <div className="main login">
fixed

2021-06-13 19:11 UTC, SupergroverNN commented on src/pages/login/Login.tsx
> +            Has no Pilot ID?
текст был взят из утвержденного дизайна =)

2021-06-13 19:22 UTC, SupergroverNN commented on src/pages/login/Login.tsx
> +            Has no Pilot ID?
fixed

2021-06-13 19:22 UTC, SupergroverNN commented on src/pages/menu/Menu.tsx
> +import './menu.scss';
fixed

2021-06-13 19:23 UTC, SupergroverNN commented on src/pages/menu/Menu.tsx
> +    <div className="menu">
зачем меню в форму?

2021-06-13 19:24 UTC, SupergroverNN commented on src/pages/menu/Menu.tsx
> +        <h1>SpaceY</h1>
fixed

2021-06-13 19:25 UTC, SupergroverNN commented on src/pages/menu/Menu.tsx
> +            const key = `${i}-${item.title}`;
действительно.

2021-06-13 19:26 UTC, SupergroverNN commented on src/pages/menu/Menu.tsx
> +            const key = `${i}-${item.title}`;
fixed

2021-06-13 19:27 UTC, SupergroverNN commented on src/pages/profile/Profile.tsx
> +import Button from '../../components/button/Button';
fixed

2021-06-13 19:27 UTC, SupergroverNN commented on src/pages/profile/Profile.tsx
> +    <div className="main">
fixed

2021-06-13 19:28 UTC, SupergroverNN commented on src/pages/signup/Signup.tsx
> +    <div className="main">
fixed

2021-06-13 19:31 UTC, SupergroverNN commented on src/pages/signup/Signup.tsx
> +        <h1>SpaceY</h1>
вот прям настолько DRY ?

2021-06-13 19:36 UTC, SupergroverNN commented on src/components/input/Input.tsx
> +      <span className="title">{title}</span>
span => label - fixed.

2021-06-13 19:41 UTC, SupergroverNN commented on src/components/input/Input.tsx
> +      <span className="title">{title}</span>
добавлена возможность использования без лейбла

2021-06-13 19:42 UTC, SupergroverNN commented on src/pages/login/Login.tsx
> +        <h1>SpaceY</h1>
fixed

2021-06-13 19:44 UTC, SupergroverNN commented on src/pages/menu/menu.scss
> +}
если честно, не понял про что ты.

2021-06-13 20:08 UTC, SupergroverNN commented on src/components/button/button.scss
> +  background-color: #36535b;
вынес все цвета в переменные, даже если они использовались один раз

2021-06-13 20:11 UTC, SupergroverNN commented on src/components/button/button.scss
> +  background-color: #36535b;
кнопка была обучена состояниям

2021-06-13 20:39 UTC, SupergroverNN commented on src/pages/login/Login.tsx
> +          <Link to="/signup" className="link">
А есть ли смысл для линка в данном случае делать отдельный компонент в который будет передаваться все тоже самое что и в сам линк и код это никак не сократит?

2021-06-13 20:39 UTC, SupergroverNN commented on src/pages/menu/menu.scss
> +  .menu-item {
fixed

2021-06-13 22:27 UTC, ValeriaKoliagina commented on src/pages/menu/Menu.tsx
> +    <div className="menu">
Меня запутало название компонента, может ты имел в виду Menu, a не Signup?

2021-06-14 18:51 UTC, ValeriaKoliagina commented on src/components/button/Button.tsx
> +    <button type={type} className={`one-button ${className}`} onClick={onClick}>{text}</button>
Привет! Спасибо, что добавил) Но в такой реализации при непередаче className у тебя класс будет 
`one-button undefined`

2021-06-14 18:51 UTC, ValeriaKoliagina commented on src/components/button/button.scss
> +  font-size: 18px;
Как считаешь, может есть смысл для font-size тоже создать переменную? вряд ли у нас их будет много, а так будет понятно, когда какой надо использовать (если хорошо назвать).

2021-06-14 18:51 UTC, ValeriaKoliagina commented on src/components/button/button.scss
> +  line-height: 100%;
Подскажи, пожалуйста, а на то влияет line-height: 100%? Не совсем понимаю, это больше обычной высоты?..

2021-06-14 18:51 UTC, ValeriaKoliagina commented on src/components/button/button.scss
> +  }
Если ты используешь одинаковые стили для ховера и эктива, можно их объединить в одно (указать стили через запятую)

2021-06-14 18:51 UTC, ValeriaKoliagina commented on src/components/input/Input.tsx
> +interface IInput {
Добавь, пожалуйста, пустую строку перед интерфейсом, чтобы разграничивать, где заканчиваются импорты и начинается что-то другое

2021-06-14 18:51 UTC, ValeriaKoliagina commented on src/components/input/Input.tsx
> +  noLabel?: boolean;
А нам нужна переменная noLabel? Можно же просто проверить на передачу непосредственное title

2021-06-14 18:51 UTC, ValeriaKoliagina commented on src/components/input/Input.tsx
> +  const { onChange, name, type = 'text', title = name, errorText, placeholder, noLabel } = props;
Я бы не присваивала в title name, как мне кажется, оно будет редко совпадать, и это позволит уйти от переменной noLabel

2021-06-14 18:51 UTC, ValeriaKoliagina commented on src/constants/commonConstants.ts
> +  LEADERBOARD: 'LEADERBOARD'
Удобнее было бы выстроить их по алфавиту, так как при большом количестве переменных - можно просто потеряться в них. Но это на твое усмотрение

2021-06-14 18:51 UTC, ValeriaKoliagina commented on src/pages/dashboard/Dashboard.tsx
> +      <form className="content">
Извини, я перепутала в прошлый раз. У тебя назывался компонент Signup и я исходя из названия предположила, что там должна быть форму. А тут форма вроде как и не нужна...

2021-06-14 18:51 UTC, ValeriaKoliagina commented on src/pages/login/Login.tsx
> +          <Link to="/signup" className="link">
Это тоже на твое усмотрение, просто мне кажется было бы удобным не передавать каждый раз класс и стили положить рядом с линкой - чтобы не засорять основной scss

2021-06-14 18:51 UTC, ValeriaKoliagina commented on src/pages/profile/Profile.tsx
> +          <img src="src/assets/images/cross.png" alt="close button" className="close-button" />
Круто, что не забываешь про alt. Спасибо)

2021-06-14 18:51 UTC, ValeriaKoliagina commented on src/style/variables.scss
> +$header_link_color: #8659ab;
Спасибо большое, что вынес в переменные, так стало более читабельно

2021-06-14 18:56 UTC, ValeriaKoliagina commented on src/pages/menu/menu.scss
> +}
Подскажи, а стили для box-shadow разные везде или одинаковые? Может можно создать какие-то переменные, которые бы говорили мне, что откуда брать? Например, если я  хочу добавить тень - то у меня уже есть переменная (а еще лучше миксина) для этого, куда я могла бы передать только цвет и у меня была бы тень, как везде по проекту. И так для остальных вещей тоже. Цвета для ховера, фокуса, эктива - если они не сильно отличаются от базового цвета, можно было бы делать через darken к примеру, наверняка в scss есть подобная функция, которая от основного цвета делает его темнее или светлее. Таким образом, мы могли бы поменять всю тему сразу

2021-06-14 18:56 UTC, ValeriaKoliagina commented on src/pages/signup/Signup.tsx
> +        <h1>SpaceY</h1>
Это по твоему усмотрению)

2021-06-15 16:18 UTC, SupergroverNN commented on src/components/button/button.scss
> +  font-size: 18px;
fixed, надеюсь нормально назвал)

2021-06-15 16:23 UTC, SupergroverNN commented on src/components/button/button.scss
> +  line-height: 100%;
fixed. стиль был взят из фигмы, на случай переопределения данного параметра глобально кем то)

2021-06-15 16:25 UTC, SupergroverNN commented on src/components/button/button.scss
> +  }
я подбирал их и оказалось что они в итоге стали одинаковые. fixed.

2021-06-15 16:29 UTC, SupergroverNN commented on src/components/input/Input.tsx
> +interface IInput {
![Screenshot 2021-06-15 at 19 28 12](https://user-images.githubusercontent.com/40541530/122089923-ecf14c00-ce0f-11eb-9e6b-5f150825d8fd.png)
ох уж этот гитлинз.. fixed

2021-06-15 16:30 UTC, SupergroverNN commented on src/constants/commonConstants.ts
> +  LEADERBOARD: 'LEADERBOARD'
fixed

2021-06-15 16:31 UTC, SupergroverNN commented on src/pages/dashboard/Dashboard.tsx
> +      <form className="content">
fixed

2021-06-15 16:33 UTC, SupergroverNN commented on src/pages/profile/Profile.tsx
> +          <img src="src/assets/images/cross.png" alt="close button" className="close-button" />
про линк, их же 2 варианта один menu-item, второй link , получается что класс все равно надо передавать)

2021-06-15 16:47 UTC, SupergroverNN commented on src/components/button/Button.tsx
> +    <button type={type} className={`one-button ${className}`} onClick={onClick}>{text}</button>
fixed

2021-06-15 16:48 UTC, SupergroverNN commented on src/pages/menu/menu.scss
> +}
box-shadow все разные, лишь цвет один у них, но он вынесен в переменную.

2021-06-15 16:55 UTC, SupergroverNN commented on src/pages/signup/Signup.tsx
> +        <h1>SpaceY</h1>
я еще раз над этим подумал и мой организм пока не готов это принять...)) оставил пока без изменений

2021-06-15 20:19 UTC, ValeriaKoliagina commented on src/components/input/Input.tsx
> +        disabled={disabled || !onChange}
Не совсем понятно, зачем нам тут 2 зависимости? Если мы не будем разрешать менять инпут - то передадим disabled. А какой может быть случай, когда не передаем disabled и не передаем onChange? Или я что-то не так понимаю?

2021-06-15 20:19 UTC, ValeriaKoliagina commented on src/constants/commonConstants.ts
> +];
У меня в ПР (который сейчас Антон смотрит), есть константы для рутов, можно будет их заюзать. Также я немного по-другому их пишу, надо придумать одинаковый подход

2021-06-15 20:19 UTC, ValeriaKoliagina commented on src/pages/dashboard/Dashboard.tsx
> +        {MENU_ITEMS.map(item => (
можно использовать деструктуризацию, вместо `title` писать `{ title, route}` - но это уже на твое усмотрение

2021-06-15 20:19 UTC, ValeriaKoliagina commented on src/pages/dashboard/Dashboard.tsx
> +      <Link to="/leaderboard" className="menu-item">
Тут тоже надо будет использовать константу (просто не забыть потом поправить). Тут и в остальных местах

2021-06-15 20:19 UTC, ValeriaKoliagina commented on src/pages/profileEdit/ProfileEdit.tsx
> +import { fakeOnChange, fakeOnClick } from 'utils';
мы же вроде решили писать сначала внешние импорты, потом внутренние

2021-06-15 20:19 UTC, ValeriaKoliagina commented on src/style/variables.scss
> +$small_font_size: 9px;
Круто, спасибо большое!

2021-06-16 09:54 UTC, SupergroverNN commented on src/components/input/Input.tsx
> +        disabled={disabled || !onChange}
Это на случай если у нас есть инпут с onChange но при этом он может быть задизейблен.

2021-06-16 09:57 UTC, SupergroverNN commented on src/pages/profileEdit/ProfileEdit.tsx
> +import { fakeOnChange, fakeOnClick } from 'utils';
fixed

2021-06-16 09:57 UTC, SupergroverNN commented on src/pages/dashboard/Dashboard.tsx
> +        {MENU_ITEMS.map(item => (
fixed

2021-06-16 10:01 UTC, SupergroverNN commented on src/pages/dashboard/Dashboard.tsx
> +      <Link to="/leaderboard" className="menu-item">
хорошо

2021-06-16 10:28 UTC, ValeriaKoliagina commented on src/pages/dashboard/Dashboard.tsx
>              {item.title}
Забыл поправить

2021-06-16 10:28 UTC, ValeriaKoliagina commented on src/pages/dashboard/Dashboard.tsx
> +          const { title, route } = item;
Можно сделать деструктуризацию прямо тут: {MENU_ITEMS.map({ title, route }) => {

2021-06-16 10:31 UTC, ValeriaKoliagina commented on src/components/input/Input.tsx
> +        disabled={disabled || !onChange}
То есть у нас может быть возможность изменять задизебленный инпут? Звучит как-то странно...

2021-06-16 12:44 UTC, SupergroverNN commented on src/components/input/Input.tsx
> +        disabled={disabled || !onChange}
нажали edit и он стал доступным для изменений))

2021-06-16 13:03 UTC, SupergroverNN commented on src/constants/commonConstants.ts
> +];
fixed

2021-06-16 13:03 UTC, SupergroverNN commented on src/pages/dashboard/Dashboard.tsx
>              {item.title}
fixed

2021-06-16 13:03 UTC, SupergroverNN commented on src/pages/dashboard/Dashboard.tsx
> +          const { title, route } = item;
fixed

2021-06-16 13:05 UTC, SupergroverNN commented on src/components/input/Input.tsx
> +        disabled={disabled || !onChange}
убрал, чтобы тебя не раздражал disabled пропс)))

2021-06-16 13:40 UTC, ValeriaKoliagina commented on src/pages/dashboard/Dashboard.tsx
> -import React, { FC, ReactElement } from 'react';
Мне кажется, можно было бы везде такой подход оставить...

2021-06-16 13:42 UTC, ValeriaKoliagina commented on src/components/input/Input.tsx
> +        disabled={disabled || !onChange}
Он меня не раздражал) Я просто пытаюсь понять логику)

2021-06-16 13:48 UTC, ValeriaKoliagina approved these changes

2021-06-17 18:20 UTC, kotosha-real requested changes
Ты проделал большую работу, красавец!
Я оставил комментарии. Ознакомься, если с чем-то несогласен или хочешь внести какие-то контрпредложения, смело пиши в реплаи к комментам, обсудим и найдём лучшее решение

2021-06-17 18:20 UTC, kotosha-real commented on src/components/button/Button.tsx
> +interface IButton {
Первое. Отбиваем все блоки импорты одной пустой строкой.
Второе. У Леры в пре интерфейсы не были помечены через заглавную I в начале. Есть какая-то договорённость в команде на этот счёт? Если да и правда за IInterface неймингом, то хорошо, если нет, то надо будет поправить.
Вариант ниже у Леры в аппрувнутом пре.

```
interface Props {
  clearState: () => void
}

const Oops: FC<Props> = ({ clearState }): ReactElement => ...
```

2021-06-17 18:20 UTC, kotosha-real commented on src/components/button/Button.tsx
> +const Button = (props: IButton): React.ReactElement => {
Давай пометим саму функцию как FC (пример в комменте выше)
Так же было бы круто деструктурировать пропсы прямо тут, а не в теле функции

2021-06-17 18:20 UTC, kotosha-real commented on src/components/button/Button.tsx
> +    <button type={type} className={`one-button${className ? ' ' + className : ''}`} onClick={onClick}>{text}</button>
Давай внедрим [classnames](https://github.com/JedWatson/classnames). Написание классов станет удобным и декларативным

2021-06-17 18:20 UTC, kotosha-real commented on src/components/button/button.scss
> +  :active {
Забыт амперсанд

2021-06-17 18:20 UTC, kotosha-real commented on src/components/button/button.scss
> +  font-size: $base_font_size;
Очень хочется с `cursor: pointer;` для кнопки

2021-06-17 18:20 UTC, kotosha-real commented on src/components/button/button.scss
> +.one-button {
Почему именно one-button?)

2021-06-17 18:20 UTC, kotosha-real commented on src/components/button/Button.tsx
> +  text: string;
Здесь точно не нужен text, это надо разрулить через children. Не только кнопка станет более юзабельной, так как в неё можно будет передать больше разного контента, но ещё и компонент будет более интуитивно понятный и без лишнего пропса

2021-06-17 18:20 UTC, kotosha-real commented on src/components/input/Input.tsx
> +  const { onChange, name, type = 'text', title, errorText, placeholder } = props;
Я не буду повторяться во всех файлах, чтобы не нудеть, но лучше:
1. Типизировать функцию через FC
2. Десктруктурировать пропсы сразу, а не в теле функции

2021-06-17 18:20 UTC, kotosha-real commented on src/components/input/Input.tsx
> +        type={type} />
Если не прибегать к использованию сторонних либ для создания форм, то лучше использовать подход [controlled components](https://reactjs.org/docs/forms.html). В статье написано, что это, как это и почему оно того стоит

2021-06-17 18:20 UTC, kotosha-real commented on src/components/input/input.scss
> +  @media screen and (max-width: $max_content_width) {
Если это не диктуется линтером, то лучше спрятать в конец (перед .title в нашем случае). Точно надо отбить медиаправило снизу пустой строкой

2021-06-17 18:20 UTC, kotosha-real commented on src/components/input/input.scss
> +  input:-webkit-autofill,
Лучше соблюдать такую структуру:
1. Стили самого блока
2. Его модификаторы
3. Медиаправила для него и его медиаправил
4. Вложенные теги
5. Вложенные классы

Сейчас вложенные теги тусят в бутерброде между вложенными классами и это не прикольно

2021-06-17 18:20 UTC, kotosha-real commented on src/components/input/input.scss
> +  .error_message {
Есть причина почему тут `_`, хотя тот же `one-input-block` использует кебаб кейс?

2021-06-17 18:20 UTC, kotosha-real commented on src/components/input/input.scss
> +      transition: opacity 0.3s;
Лигшее, транзишен для правила на 36 строке никуда не убежит

2021-06-17 18:20 UTC, kotosha-real commented on src/pages/dashboard/Dashboard.tsx
> -import React, { FC, ReactElement } from 'react';
Плюс за такой подход. Давайте придерживаться его. Компоненты станут читабельнее, тайпинги не будут такими объёмными

2021-06-17 18:20 UTC, kotosha-real commented on src/index.tsx
>  import App from './App';
Отделяем все блоки импортов одной пустой строкой, стили в самом конце

```suggestion

import App from './App';

import 'style/main.scss';
```

2021-06-17 18:20 UTC, kotosha-real commented on webpack.config.js
> +    filename: filename('js')
Странно, что ты убрал эти запятые, хотя, в конфиге преттиера указана опция `"trailingComma": "all"`

2021-06-17 18:20 UTC, kotosha-real commented on src/pages/dashboard/Dashboard.tsx
> +        }
```suggestion
        {MENU_ITEMS.map(({ title, route }) => {
          return (
            <Link key={title} className="menu-item" to={route}>
              {title}
            </Link>
          )}
        )}
```

2021-06-17 18:20 UTC, kotosha-real commented on src/pages/dashboard/dashboard.scss
> +  &-item {
Через амперсанд лучше отбивать только состояния, например, `:disabled`/`_disabled` для кнопки. Если это отдельная сущность, то писать отдельно. Так будет удобнее и для поиска по проекту, и в целом будет более строго и последовательно

2021-06-17 18:20 UTC, kotosha-real commented on src/pages/login/login.scss
> +  @media screen and (max-width: $max_content_width) {
Было выше про расположение медиаправил. Если что, то это вполне дискуссионная тема, если команде так удобно, то всё ок

2021-06-17 18:20 UTC, kotosha-real commented on src/style/variables.scss
> +$error_main_color: #db4e3f;
Есть ли нужна в слове main в составе переменных? С таким неймингом кажется, что переменные что-то связывает, хотя, это не так

2021-06-17 18:20 UTC, kotosha-real commented on src/style/common.scss
> +  h1 {
Это хорошая последовательность: сначала отбиваем все состояния элемента, потом пишем вложенные селекторы 👍🏻

2021-06-17 18:20 UTC, kotosha-real commented on src/style/common.scss
> +    &.double {
А вот тут надо ревертнуть в соответствии с комментом выше)

2021-06-17 18:27 UTC, ValeriaKoliagina commented on src/components/button/Button.tsx
> +interface IButton {
Да, лучше поправить в моем варианте. Только вопрос, что лучше и когда лучше использовать, интерфейсы или типы?

2021-06-17 20:48 UTC, SupergroverNN commented on src/components/button/button.scss
> +  font-size: $base_font_size;
fixed

2021-06-17 20:48 UTC, SupergroverNN commented on src/components/button/button.scss
> +  :active {
fixed

2021-06-17 20:52 UTC, SupergroverNN commented on src/components/button/Button.tsx
> +interface IButton {
удалил гитлинз, имитирует пустые строки в некоторых случаях. Попадаюсь не первый раз.

2021-06-17 21:04 UTC, SupergroverNN commented on src/components/button/Button.tsx
> +interface IButton {
fixed

2021-06-17 21:05 UTC, SupergroverNN commented on src/components/button/Button.tsx
> +const Button = (props: IButton): React.ReactElement => {
fixed

2021-06-17 21:05 UTC, SupergroverNN commented on src/pages/dashboard/dashboard.scss
> +  &-item {
fixed

2021-06-17 21:07 UTC, SupergroverNN commented on src/pages/dashboard/Dashboard.tsx
> -import React, { FC, ReactElement } from 'react';
fixed

2021-06-17 21:18 UTC, SupergroverNN commented on src/style/variables.scss
> +$error_main_color: #db4e3f;
предполагалось, что будет главный , второстепенный и еще какой нибудь вариант

2021-06-17 21:24 UTC, SupergroverNN commented on src/style/common.scss
> +    &.double {
расположил в соответствии с правилом stylelint. 
<img width="898" alt="Screenshot 2021-06-18 at 00 23 29" src="https://user-images.githubusercontent.com/40541530/122474202-916bbd80-cfcb-11eb-91c3-a485b549ef4f.png">

2021-06-17 21:29 UTC, SupergroverNN commented on src/pages/login/login.scss
> +  @media screen and (max-width: $max_content_width) {
раньше, описывал стили, сначала общие, потом все медиа - отдельными блоками. На курсах от Epam рассказывали о таком способе, типа удобно, все в одном месте, не нужно мотать туда сюда стили для переопределения свойств. выглядит более громоздко, но зато все рядом. Если это плохой тон, то переделаю.

2021-06-17 21:44 UTC, SupergroverNN commented on src/components/button/Button.tsx
> +    <button type={type} className={`one-button${className ? ' ' + className : ''}`} onClick={onClick}>{text}</button>
fixed

2021-06-18 04:50 UTC, kotosha-real commented on src/style/common.scss
> +    &.double {
А в ситуации выше не ругается?

2021-06-18 05:17 UTC, kotosha-real reviewed
Докинул ещё комментов

2021-06-18 05:17 UTC, kotosha-real commented on package.json
> +    "classnames": "^2.3.1",
Надо запинить версию

2021-06-18 05:17 UTC, kotosha-real commented on src/components/button/Button.tsx
> +    // <button type={type} className={`one-button${className ? ' ' + className : ''}`} onClick={onClick}>{text}</button>
Если коммент был нужен только для референса во время переписывания на classNames, то давай сотрём

2021-06-18 05:17 UTC, kotosha-real commented on src/components/button/Button.tsx
> +import classNames from 'classnames';
Не критично, но лучше импортировать как `cn` или выбрать другую аббревиатуру. Будет короче и не так громоздко смотреться в jsx

2021-06-18 05:17 UTC, kotosha-real commented on src/components/button/Button.tsx
> +interface IButton {
@ValeriaKoliagina я за интерфейсы. Ими принято описывать интерфейс какого-то класса или функции, в то время как типами логичнее отбивать конкретные поля, переменные, всё такое
Ещё есть [статья](https://dev.to/reyronald/typescript-types-or-interfaces-for-react-component-props-1408) а этот счёт, почитай)

2021-06-18 05:17 UTC, kotosha-real commented on src/components/button/Button.tsx
> +interface IButton {
@ValeriaKoliagina @SupergroverNN 
И давайте насчёт нейминга пропсов договоримся. Если оставим тут префиксы, то нужно будет потом в рамках техдлолга затащить их в другие интерфейсы тоже

2021-06-18 05:17 UTC, kotosha-real commented on src/pages/profileEdit/ProfileEdit.tsx
> +import { fakeOnChange, fakeOnClick } from 'utils';
utils перед constants (так у тебя, например в `Login.tsx`). Или наоборот, но точно не между

2021-06-18 05:17 UTC, kotosha-real commented on src/pages/profile/Profile.tsx
> +          <div className="input-wrapper double">
Смущает множественный double. Судя по другим файлам, он юзается только там. где есть поля, зачем тащить его в .content и тем более .content-wrapper? Сейчас это выглядит очень связно: если ты захочешь сделать такую же форму, то тебе будет недостаточно перетащить разметку самих полей, тебе нужно будет ещё и менять контентные дивы, в которых они лежат, чтобы получить ожидаемый результат. Это нужно будет переработать. Возможно, не в этом пре, чтобы не задерживаться на нём, но в рамках техдолга точно

2021-06-18 17:25 UTC, SupergroverNN commented on src/style/common.scss
> +    &.double {
нет)

2021-06-18 17:26 UTC, SupergroverNN commented on package.json
> +    "classnames": "^2.3.1",
fixed

2021-06-18 17:26 UTC, SupergroverNN commented on src/components/button/Button.tsx
> +    // <button type={type} className={`one-button${className ? ' ' + className : ''}`} onClick={onClick}>{text}</button>
ой ой
fixed

2021-06-18 17:28 UTC, SupergroverNN commented on src/components/button/Button.tsx
> +import classNames from 'classnames';
fixed

2021-06-18 17:30 UTC, SupergroverNN commented on src/pages/profileEdit/ProfileEdit.tsx
> +import { fakeOnChange, fakeOnClick } from 'utils';
fixed

2021-06-18 17:44 UTC, SupergroverNN commented on src/pages/profile/Profile.tsx
> +          <div className="input-wrapper double">
fixed

2021-06-19 03:22 UTC, SupergroverNN commented on src/components/button/button.scss
> +.one-button {
типа одно что-то))one-button, one-input-block.. ))

2021-06-19 03:25 UTC, SupergroverNN commented on webpack.config.js
> +    filename: filename('js')
теперь стоит "all", до этого стояло "none"

2021-06-19 03:30 UTC, SupergroverNN commented on src/components/input/input.scss
> +  @media screen and (max-width: $max_content_width) {
fixed

2021-06-19 03:31 UTC, SupergroverNN commented on src/components/input/input.scss
> +  .error_message {
fixed

2021-06-19 03:31 UTC, SupergroverNN commented on src/components/input/input.scss
> +      transition: opacity 0.3s;
fixed

2021-06-19 03:34 UTC, SupergroverNN commented on src/index.tsx
>  import App from './App';
fixed

2021-06-19 03:35 UTC, SupergroverNN commented on webpack.config.js
> +    filename: filename('js')
fixed

2021-06-19 03:38 UTC, SupergroverNN commented on src/pages/dashboard/Dashboard.tsx
> +        }
fixed

2021-06-19 03:39 UTC, SupergroverNN commented on src/components/input/Input.tsx
> +  const { onChange, name, type = 'text', title, errorText, placeholder } = props;
fixed

2021-06-19 03:43 UTC, SupergroverNN commented on src/components/button/Button.tsx
> +  text: string;
fixed (надеюсь)

2021-06-19 04:19 UTC, SupergroverNN commented on src/components/input/Input.tsx
> +        type={type} />
я не совсем понял что нужно сделать с инпутом. Если относительно формы, то как будто добавить онсабмит хендлер с preventDefault

2021-06-19 04:43 UTC, SupergroverNN commented on src/components/button/Button.tsx
> +  text: string;
fixed

2021-06-20 07:15 UTC, kotosha-real reviewed
Почти готово. Посмотри оставшиеся комменты

2021-06-20 07:15 UTC, kotosha-real commented on src/components/input/input.scss
> +      transition: opacity 0.3s;
Здесь надо было убрать, а там наоборот оставить. Раньше было плавное поведение всегда, сейчас только при появлении

2021-06-20 07:15 UTC, kotosha-real commented on src/components/input/Input.tsx
> +        type={type} />
Передать ему `value` из компонента, который его рендерит и на `onChange` вызывать коллбэк (это уже есть). Почему так лучше: компонент инпута не должен знать и хранить информацию о том, что он выводит, это задача компонента с формой. Так у тебя возможны ситуации, в которых компонент формы и сам инпут будут иметь разные состояния, и это совсем не весело дебажить)
Изменение будет всего одно, ты добавишь value в пропсы, а потом передашь в качестве параметра инпуту

2021-06-20 07:15 UTC, kotosha-real commented on webpack.config.js
> +      images: `${__dirname}/src/assets/images`
Есть правило в конфиге преттиера `"trailingComma": "all"`, добавь везде, где нужно запятые в конце каждого поля

2021-06-20 07:15 UTC, kotosha-real commented on src/components/input/Input.tsx
> +    <div className="one-input-block">
Тут ещё хорошо бы докрутить условное присваивание класса error. В стилях есть, получить его нельзя

2021-06-20 16:41 UTC, SupergroverNN commented on src/components/input/input.scss
> +      transition: opacity 0.3s;
fixed

2021-06-20 17:03 UTC, SupergroverNN commented on src/components/input/Input.tsx
> +    <div className="one-input-block">
fixed

2021-06-20 17:06 UTC, SupergroverNN commented on webpack.config.js
> +      images: `${__dirname}/src/assets/images`
fixed

2021-06-20 17:43 UTC, kotosha-real approved these changes
Я добавил три коммента. Добей и можно мержить)
🕵🏻‍♂️

2021-06-20 17:43 UTC, kotosha-real commented on src/pages/login/Login.tsx
> +  const [state] = useState({
❗️
Добавь сразу сеттер

2021-06-20 17:43 UTC, kotosha-real commented on src/constants/commonConstants.ts
> +export const defaultUserState = {
❗️
Все константы надо писать в одном формате
```suggestion
export const DEFAULT_USER_STATE = {
```

2021-06-20 17:43 UTC, kotosha-real commented on webpack.config.js
> +        use: [ 'style-loader', 'css-loader', 'sass-loader' ]
❗️
trailing-запятые везде в файле надо проставить)

2021-06-20 18:15 UTC, SupergroverNN commented on webpack.config.js
> +        use: [ 'style-loader', 'css-loader', 'sass-loader' ]
надо в дальнейшем синхронизировать преттир с еслинтом. А-то сами запятые не ставятся в некоторых ситуциях =(
fixed

2021-06-20 18:16 UTC, SupergroverNN commented on src/constants/commonConstants.ts
> +export const defaultUserState = {
fixed

2021-06-20 18:33 UTC, StopNGo commented on webpack.config.js
> +        use: [ 'style-loader', 'css-loader', 'sass-loader' ]
Для этого тут https://github.com/Yandex-SpaceY/SpaceY/pull/10 мы с Лерой добавили https://www.npmjs.com/package/prettier-eslint
Надо что бы ты потом после мерджа со своей стороны проверил, все ли работает, как надо.

2021-06-20 18:33 UTC, SupergroverNN commented on src/pages/login/Login.tsx
> +  const [state] = useState({
fixed

2021-06-20 18:40 UTC, merged