API для авторизации, регистрации и работы с профилем
Yandex-SpaceY/SpaceY pull request #7
Opened 2021-06-17 18:13 UTC by ValeriaKoliagina

Созданы ручки, надо будет их подключить (сейчас нету разметки)

2021-06-17 21:51 UTC, SupergroverNN approved these changes

2021-06-18 07:45 UTC, SupergroverNN commented
> Созданы ручки, надо будет их подключить (сейчас нету разметки)

2021-06-18 22:43 UTC, kotosha-real requested changes
Хорошая работа!
Есть то, что нужно поменять, и то, что стоит обсудить. Смело пингуй, если что-то будет непонятно

2021-06-18 22:43 UTC, kotosha-real commented on src/utils/api.ts
> +export enum METHODS {
Когда экспорты идут вперемежку с обычными данными, то лучше перечислить их в объекте в конце файла

2021-06-18 22:43 UTC, kotosha-real commented on src/constants/errorConstants.ts
> +  FILL_FIELD: 'Cannot be blank',
Сообщения об ошибке должны описывать, что не так, а не призывать к действию)

```suggestion
  FIELD_EMPTY: 'Cannot be blank',
```

2021-06-18 22:43 UTC, kotosha-real commented on src/components/oops/Oops.tsx
> +    <Link to={ROUTE_CONSTANTS.DASHBOARD} onClick={clearState}>Go to dashboard</Link>
Все эти изменения (что в этом, что в других файлах) кажутся лишними, так как они есть в пре Игоря

2021-06-18 22:43 UTC, kotosha-real commented on src/utils/api.ts
> +export const api = async (
Круто, что ты решила затащить апи сама, но я бы прям супер рекомендовал юзать [axios](https://github.com/axios/axios), когда нет на это ограничений

Если хочется остаться со своим решением, то api должен быть классом с определёнными методами. Хочется вызывать его как `api.get(url)` или `api.post(url, body)`. Они все под капотом могут юзать фетч, но использование станет более понятным

2021-06-18 22:43 UTC, kotosha-real commented on src/api/authApi.ts
> +import { api, METHODS, Result } from 'utils';
METHODS — константа, но она тут совсем не нужна. Я предлагаю api реализовать иначе: api будет инстансом JS-класса, которые имеет методы get/post/put/delete. В файлах по типу этого, где ты задаёшь роуты, не понадобятся методы, ты будешь дёргать `api.get(url)` и радоваться)
Также api не нужно выносить в utils, логичнее расположить его в этой папке

2021-06-18 22:43 UTC, kotosha-real commented on src/constants/routeConstants.ts
> +  LOGOUT: '/logout',
Писал выше, это не константы роутов. Тут перечисляем только роуты приложения
Это касается всего добавленного для апи

2021-06-18 22:43 UTC, kotosha-real commented on src/api/authApi.ts
> +import { ROUTE_CONSTANTS } from 'constants/routeConstants';
Это не константы роутов. В том файле мы пишем роуты приложения, то есть тех страниц, куда мы можем перейти. Апишные эндпоинты могут лежать тут же, так будет удобнее всем: они будут юзаться только здесь, поэтому смысла их выносить в отдельные константы нет

2021-06-18 22:43 UTC, kotosha-real commented on src/api/authApi.ts
> +  api(`${URL_CONSTANTS.AUTH}${ROUTE_CONSTANTS.SIGNUP}`, METHODS.POST, JSON.stringify(payload))
Подход выше позволит избежать:
1. Склеивания разных по сути констант в эндпоинт
2. Явного указания метода в параметрах

Сравни:
```suggestion
  api.post(RequestRoot.signUp, JSON.stringify(payload))
```

Под RequestRoot имею enum роутов для авторизации, написанный тут же

2021-06-18 22:43 UTC, kotosha-real commented on src/utils/validations.ts
> +const checkEmail = (email: string): string => {
Они на будущее? Пока не вижу, чтобы использовались где-то в проекте

2021-06-18 22:43 UTC, kotosha-real commented on src/utils/validations.ts
> +  return pattern.test(email) ? '' : ERROR_CONSTANTS.EMAIL_INVALID;
В таких функциях в ответе хочется получить `true`/`false`

Если рассмотреть вопрос валидации более глобально, то в качестве бест практис можно посмотреть на связку Formik + Yup вот [тут](https://habr.com/ru/post/418921/), потому что это правда удобно

2021-06-19 11:23 UTC, ValeriaKoliagina commented on src/utils/validations.ts
> +const checkEmail = (email: string): string => {
Да, я решила добавить сразу валидацию, так как оно=а все равно понадобится при подключении ручек

2021-06-19 11:25 UTC, ValeriaKoliagina commented on src/utils/validations.ts
> +  return pattern.test(email) ? '' : ERROR_CONSTANTS.EMAIL_INVALID;
Про true/false думала, но это значит, везде где будет использоваться данная проверка, надо будет еще добавлять константы ошибок. Поскольку приложение небольшое и не подразумевает использование одних и тех же валидаций под разные кейсы, решила сразу возвращать ошибку

2021-06-19 11:25 UTC, ValeriaKoliagina commented on src/constants/errorConstants.ts
> +  FILL_FIELD: 'Cannot be blank',
у мне была мысль, но как написать: имейл должен содержжать собачку, точку и 2 или 3 знака после точки? ну такое себе... а если разбивать ошибки, то по мне это ужасно. Ваш пароль не той длины - ок исправил, а в вашем пароль нету - ок, добавил, а теперь тут не хватает большой буквы - я бы просто ушла с такого сайта. А телефон проверяет довольно много условий, тоже не совсем представляю как тогда это лучше написать. Тем более, что в каждом поле будут плейсхолдеры с образцом заполнения

2021-06-19 14:29 UTC, kotosha-real commented on src/constants/errorConstants.ts
> +  FILL_FIELD: 'Cannot be blank',
Я бы максимум написал пример валидного мыла, остальное уже лишнее. Что касается пароля и других полей с кастомными требованиями, то пиши максимально просто: "Пароль невалидный, убедитесь, что есть цифра, буква, символ"

2021-06-20 06:58 UTC, kotosha-real approved these changes
Молодец!

🕵🏻‍♂️

2021-06-20 06:58 UTC, kotosha-real commented on src/constants/routeConstants.ts
> +  LOGIN: '/login',
Плюс за соблюдение порядка)

2021-06-20 06:58 UTC, kotosha-real commented on src/api/api.ts
> +  responseType: 'json',
Кажется, что тут ещё нужно `withCredentials: true`
И таймаут тоже лишним не будет

2021-06-20 07:53 UTC, ValeriaKoliagina commented on src/api/api.ts
> +  responseType: 'json',
Добавила

2021-06-20 08:11 UTC, merged