Game component
Yandex-SpaceY/SpaceY pull request #8
Opened 2021-06-19 16:24 UTC by StopNGo

2021-06-19 18:50 UTC, SupergroverNN approved these changes

2021-06-20 01:09 UTC, StopNGo commented
Добавлено черновое меню по ESC (пауза), с возобновление и рестартом игры.

2021-06-20 10:07 UTC, kotosha-real requested changes
Большая работа, много кода, ты молодец!
Оставил комменты, в слаке описал как реагировать на каждый из вариантов, посмотри их, если есть вопросы задавай тут или в слаке

2021-06-20 10:07 UTC, kotosha-real commented on src/pages/game/Game.tsx
> +  );
❗️
```suggestion
  return (
    <div>
      <GameCanvas></GameCanvas>
      <Link to={routeConstants.DASHBOARD}>Go to dashboard</Link>
    </div>
  );
```

2021-06-20 10:07 UTC, kotosha-real commented on src/components/gamecanvas/GameCanvas.tsx
> +  className?: string;
🧐
Лучше изменить название пропсы, чтобы явно указывать, что это проп компонента. На проектах, где я сейчас работаю, принято называть такие пропсы `mix`

2021-06-20 10:07 UTC, kotosha-real commented on src/components/gamecanvas/GameCanvas.tsx
> +      getCollisions, getScore, getGameOverStatus, getGamePauseStatus);
🧐
Когда аргументов много, лучше отбивать их с новой строки. Когда аргументов очень много, лучше паковать их в объекты. Плюс объекта в том, что не получится напортачить с последовательностью аргументов, а чем их больше, тем больше такая вероятность

```suggestion
    gameMain = new GameMain(
      canvas as HTMLCanvasElement,
      getCollisions,
      getScore,
      getGameOverStatus,
      getGamePauseStatus
    );
```

2021-06-20 10:07 UTC, kotosha-real commented on src/components/gamecanvas/GameCanvas.tsx
> +      gameMain.unsetControlsandSubscriptions();
❗️
```suggestion
      gameMain.unsetControlsAndSubscriptions();
```

2021-06-20 10:07 UTC, kotosha-real commented on src/components/gamecanvas/GameCanvas.tsx
> +import GameMain from '../../game/gamemain';
❗️
Давай сделаем либо camel-case, либо kebab-case вариант. Два слова без какого-либо визуального разделителя читаются хуже, чем с ним

2021-06-20 10:07 UTC, kotosha-real commented on src/game/gamemain.ts
> +  state: 'flight' | 'shift',
❗️
Отбей дополнительно эти строки через `enum`. Они дальше используются по коду и меньше всего хочется случайно допустить опечатку в написании. Тайпскрипт, конечно, подскажет, что ты делаешь что-то не то, но хорошим тоном будет указывать не голую строку, а, скажем, вот так: `STATE.FLIGHT`
Так будет гораздо удобнее:
1. Будет работать автодополнение
2. Можно быстро посмотреть какие значения вообще можно использовать

2021-06-20 10:07 UTC, kotosha-real commented on src/game/resources.ts
> +  private _loadSingle(url: string) {
❗️
Все ассеты надо хранить вместе с игрой

2021-06-20 10:07 UTC, kotosha-real commented on src/game/resources.ts
> +      const  img = new Image();
❗️
Лишний пробел

2021-06-20 10:07 UTC, kotosha-real commented on src/game/resources.ts
> +  load(urlOrArr: string | string[]): void {
🧐
Называть так проп не самая лучшая идея. Если есть возможность грузить несколько файлов разом, то лучше сразу передавать массив, пусть даже из одного элемента. Функция станет короче и чище

2021-06-20 10:07 UTC, kotosha-real commented on src/game/resources.ts
> +      });
🧐
```suggestion
      urlOrArr.forEach(this._loadSingle);
```

2021-06-20 10:07 UTC, kotosha-real commented on src/game/resources.ts
> +        if (this.isReady()) {
🧐
Подход хороший в плане того, что у тебя один раз вызовутся `onReady` коллбэки, но тут есть свои минусы:
1. Одна пикча может грузится очень долго и всё это время не будет происходить ничего. Когда я запустил проект из этой ветки, лаг между рефрешем страницы и появлением игры был значительным
2. Состояния ошибок не обрабатываются, если одна из ссылок протухла, то не произойдёт вообще ничего

Все эти проблемы можно избежать, сохранив все ассеты локально. Не будет ни задержек, ни лишнего кода на загрузку и обработку нештатных ситуаций при загрузке, код станет проще поддерживать

2021-06-20 10:07 UTC, kotosha-real commented on src/game/resources.ts
> +  }
❗️
Если заранее взять ключи, то проверка на `hasOwnProperty` будет не нужна
```suggestion
  isReady(): boolean {
    for (const cacheEntry of Object.keys(this.resourceCache)) {
      if (!cacheEntry) return false
    }

    return true
```

В целом старайся не писать такие длинные `if`-ы, если что-то требует большого количества проверок, то лучше вынести это в отдельную функцию, а в `if`-е использовать её результат

2021-06-20 10:07 UTC, kotosha-real commented on src/components/gamecanvas/GameCanvas.tsx
> +      <menu style={{
❗️
В текущем стандарте HTML у `<menu>` другая семантика — http://htmlbook.ru/html/menu
Надо заменить на более подходящий, тут хватит и обычного дива

2021-06-20 10:07 UTC, kotosha-real commented on src/game/sprite.ts
> +  constructor(url: string, pos: [number, number], size: [number, number], speed?: number, frames?: [number, number], dir?: 'horizontal' | 'vertical', once?: boolean) {
❗️
Как и в других местах, либо отбиваем каждый на новой строке, либо в конструктор передаём объект с данными полями, что в данном кейсе даже предпочтительно, чтобы не просыпать порядок аргументов

2021-06-20 10:07 UTC, kotosha-real commented on src/game/sprite.ts
> +    this.speed = speed === undefined ? 0 : speed;
🧐
Потребуется дополнительный [babel-плагин](https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator), но такой синтаксис уже активно юзается
```suggestion
    this.speed = speed ?? 0;
```

2021-06-20 10:07 UTC, kotosha-real commented on src/game/sprite.ts
> +    let  frame = 0;
❗️
Посмотри по коду где ещё есть лишний пробелы, мб я пропустил где-то
```suggestion
    let frame = 0;
```

2021-06-20 10:07 UTC, kotosha-real commented on src/game/sprite.ts
> +    if (this.speed !== undefined && this.frames !== undefined ) {
❗️
```suggestion
    if (this.speed !== undefined && this.frames !== undefined) {
```

2021-06-20 10:07 UTC, kotosha-real commented on src/game/sprite.ts
> +      this.size[0], this.size[1]);
❗️
Группировку можем сохранить, а вот само форматирование надо чуть подбить
```suggestion
    ctx.drawImage(
      resources.get(this.url) as CanvasImageSource,
      x, y,
      this.size[0], this.size[1],
      0, 0,
      this.size[0], this.size[1]
    );
```

2021-06-20 10:07 UTC, kotosha-real commented on src/game/sprite.ts
> +
❗️
```suggestion
```

2021-06-20 10:07 UTC, kotosha-real commented on src/game/gamemain.ts
> +type TObject = {
@ValeriaKoliagina кажется, что ребята за пометку типов и интерфейсов литералом перед именем)
Надо будет потом по всему проекту применить

2021-06-20 10:07 UTC, kotosha-real commented on src/game/gamemain.ts
> +  debris:TObject[];
```suggestion
  debris: TObject[];
```

2021-06-20 10:07 UTC, kotosha-real commented on src/components/gamecanvas/GameCanvas.tsx
> +  const [ isGamePaused, getGamePauseStatus ] = useState(false);
❗️
Это сеттеры, поэтому называть их нужно с префиксом set)
Плюс хорошим тоном будет использовать полное название поле в сеттере. Ниже привёл пример
```suggestion
  const [ collisions, setCollisions ] = useState(0);
  const [ score, getScore ] = useState(0);
  const [ isGameOver, setIsGameOverStatus ] = useState(false);
  const [ isGamePaused, setIsGamePauseStatus ] = useState(false);
```

2021-06-20 10:07 UTC, kotosha-real commented on src/game/gamemain.ts
> +    setGamePauseStatus: Dispatch<SetStateAction<boolean>>) {
❗️
```suggestion
  constructor(
    canvas: HTMLCanvasElement,
    setCollisions: Dispatch<SetStateAction<number>>,
    setScore: Dispatch<SetStateAction<number>>,
    setGameOverStatus: Dispatch<SetStateAction<boolean>>,
    setGamePauseStatus: Dispatch<SetStateAction<boolean>>
  ) {
```

2021-06-20 10:07 UTC, kotosha-real commented on src/game/gamemain.ts
> +    this.resources.onReady(this.init);
Писал в файле ресурсов, что локальные файлы устранят задержку и будет хорошо

2021-06-20 10:07 UTC, kotosha-real commented on src/game/gamemain.ts
> +    this.setGamePauseStatus(false);
🧐
Люблю отбивать разные по сути блоки пустой строкой
```suggestion
    document.removeEventListener('keydown', this.controls);
    
    this.setCollisions(0);
    this.setScore(0);
    this.setGameOverStatus(false);
    this.setGamePauseStatus(false);
```

2021-06-20 10:07 UTC, kotosha-real commented on src/game/gamemain.ts
> +    } else if (event.keyCode === 27) {
❗️
И кейкоды и сайд со стейтом надо положить в енамы. Про сайд и стейт есть объяснение в комменте в начале файла, а кейкоды невозможно читать вот так. `event.keyCode === KEY_CODE.ESC` очевидно с первого раза, тогда как голые коды надо лезть гуглить

2021-06-20 10:07 UTC, kotosha-real commented on src/game/gamemain.ts
> +    for (let i = 1; i <= numberOfWalls; i++) {
🧐
```suggestion
    const numberOfWalls = Math.ceil(this.canvas.height / 96) + 1;
    
    for (let i = 1; i <= numberOfWalls; i++) {
```
Циклы и условия лучше отбивать пустой строкой

2021-06-20 10:07 UTC, kotosha-real commented on src/game/gamemain.ts
> +  boxCollides(pos: [number, number], size: [number, number], pos2: [number, number], size2: [number, number]): boolean {
❗️
```suggestion
  boxCollides(
    pos: [number, number],
    size: [number, number],
    pos2: [number, number],
    size2: [number, number]
  ): boolean {
```

2021-06-20 10:07 UTC, kotosha-real commented on src/game/gamemain.ts
> +
```suggestion
```

2021-06-20 10:07 UTC, kotosha-real commented on src/game/gamemain.ts
> +  }
❗️
```suggestion
    return this.collides(
      pos[0], pos[1],
      pos[0] + size[0], pos[1] + size[1],
      pos2[0], pos2[1],
      pos2[0] + size2[0], pos2[1] + size2[1]
    );
  }
```

2021-06-20 10:07 UTC, kotosha-real commented on src/game/gamemain.ts
> +    for (let i = 0; i < this.debris.length; i++) {
❗️
Здесь и везде стоит использовать методы массивов, если нет очень веской причины сбиваться в императивщину
```suggestion
    this.debris.forEach(...)
```

2021-06-20 18:59 UTC, StopNGo commented on src/game/gamemain.ts
> +    for (let i = 0; i < this.debris.length; i++) {
Тут скорее всего будет все меняться, так что пока не трогаю)

2021-06-21 06:20 UTC, kotosha-real approved these changes
Стало гораздо красивее, молодец!
Оставил ещё несколько комментов, ставлю аппрув, поправь их (они короткие) и можно мержить
🕵🏻‍♂️

2021-06-21 06:20 UTC, kotosha-real commented on src/pages/game/Game.tsx
> +      <GameCanvas></GameCanvas>
❗️
В еслинте можно настроить правило, которое будет ругаться на несамозакрывающиеся теги, если в них нет детей. Это лучше использовать как железное правило везде
```suggestion
      <GameCanvas />
```

2021-06-21 06:20 UTC, kotosha-real commented on src/pages/game/Game.tsx
> +      <GameCanvas></GameCanvas>
❗️
Всегда юзай самозакрывающиеся теги, где нет детей. В еслинте есть хорошее правило на этот счёт
```suggestion
      <GameCanvas />
```

2021-06-21 06:20 UTC, kotosha-real commented on src/game/gamemain.ts
> +  collides(x: number, y: number, r: number, b: number, x2: number, y2: number, r2: number, b2: number): boolean {
❗️
Тут тоже давай всё с новой строки

2021-06-21 06:20 UTC, kotosha-real commented on src/components/gamecanvas/GameCanvas.tsx
> +          display: isGamePaused ? 'block' : 'none',
В будущем этому всему классы надо будет присвоить

2021-06-21 06:20 UTC, kotosha-real commented on src/game/gamemain.ts
> +import Resources from './resources';
❗️
Отбиваем группы импортов пустой строкой
```suggestion

import Resources from './resources';
```

2021-06-21 11:12 UTC, merged